(() => {
  "use strict";
  const $ = (s, root = document) => root.querySelector(s);
  const $$ = (s, root = document) => [...root.querySelectorAll(s)];
  const names = { constitucio:"Constitució espanyola", "39":"Llei 39/2015", "40":"Llei 40/2015", "4":"Llei orgànica 4/2015", "16":"Llei 16/1991 de les policies locals", trafic:"Normativa de trànsit" };
  const banks = {
    constitucio:[
      ["Segons la Constitució espanyola, on resideix la sobirania nacional?",["A les Corts Generals","En el poble espanyol","En el cap de l'Estat","En el Govern"],1,"L'article 1.2 estableix que la sobirania nacional resideix en el poble espanyol, del qual emanen els poders de l'Estat."],
      ["Quin article reconeix la igualtat davant la llei?",["Article 9","Article 14","Article 24","Article 30"],1,"L'article 14 proclama la igualtat davant la llei i prohibeix la discriminació pels motius que enumera."],
      ["Quina és la forma política de l'Estat espanyol?",["República parlamentària","Monarquia absoluta","Monarquia parlamentària","Estat confederal"],2,"L'article 1.3 estableix que la forma política de l'Estat espanyol és la monarquia parlamentària."],
      ["Quin dret protegeix l'article 18.1?",["El dret de reunió","El dret a l'educació","L'honor, la intimitat personal i familiar i la pròpia imatge","La llibertat sindical"],2,"L'article 18.1 garanteix el dret a l'honor, a la intimitat personal i familiar i a la pròpia imatge."],
      ["Qui exerceix la potestat legislativa de l'Estat?",["El Govern exclusivament","Les Corts Generals","El Tribunal Constitucional","El Consell General del Poder Judicial"],1,"Les Corts Generals exerceixen la potestat legislativa, aproven els pressupostos i controlen l'acció del Govern."]
    ],
    "39":[
      ["Quina matèria regula principalment la Llei 39/2015?",["El règim del personal laboral privat","El procediment administratiu comú de les administracions públiques","L'organització del poder judicial","El règim electoral general"],1,"La Llei 39/2015 regula el procediment administratiu comú de les administracions públiques."],
      ["Com es computen, amb caràcter general, els terminis assenyalats per dies?",["Sempre com a dies naturals","Com a dies hàbils, llevat que s'indiquin dies naturals","Només de dilluns a dijous","Com a dies naturals, excepte a l'agost"],1,"La regla general és el còmput en dies hàbils: s'exclouen dissabtes, diumenges i festius, llevat que s'estableixi que són naturals."],
      ["Quin és un dret de les persones interessades en un procediment?",["Exigir una resolució favorable","Conèixer l'estat de tramitació del procediment","Ometre sempre qualsevol identificació","Escollir el sentit de la resolució"],1,"La Llei reconeix el dret de les persones interessades a conèixer l'estat de tramitació del procediment."],
      ["Què ha d'incloure, en general, una notificació administrativa?",["Només el nom de l'òrgan","El text íntegre i la informació sobre els recursos procedents","Únicament la data de signatura","Sempre una còpia de tot l'expedient"],1,"La notificació ha d'incloure el text íntegre de la resolució i la informació legalment exigida sobre recursos."],
      ["Quin és, amb caràcter general, l'efecte del silenci en procediments iniciats a sol·licitud de l'interessat?",["Sempre desestimatori","Sempre estimatori sense excepcions","Estimatori, amb les excepcions legals","La nul·litat automàtica del procediment"],2,"La regla general és el silenci estimatori, amb excepcions legals en què és desestimatori."]
    ],
    "40":[
      ["Quina matèria regula principalment la Llei 40/2015?",["El règim jurídic del sector públic","El Codi penal","El procediment laboral privat","Els arrendaments urbans"],0,"La Llei 40/2015 regula les bases del règim jurídic de les administracions públiques i altres aspectes del sector públic."],
      ["Quin principi ha de respectar l'actuació administrativa?",["Arbitrarietat","Eficàcia i coordinació","Secret absolut en tots els actes","Preferència per interessos particulars"],1,"L'eficàcia i la coordinació són principis de l'actuació i de les relacions entre administracions."],
      ["Què implica el principi d'irrenunciabilitat de la competència?",["Que cada òrgan pot renunciar-hi lliurement","Que l'ha d'exercir l'òrgan que la té atribuïda, llevat dels supòsits legals","Que la competència passa automàticament a un altre òrgan","Que no existeixen delegacions"],1,"La competència és irrenunciable i l'exerceix l'òrgan que la té atribuïda, sens perjudici de les tècniques previstes legalment."],
      ["Quina figura permet encarregar l'exercici d'una competència a un altre òrgan en els termes legals?",["Delegació de competències","Renúncia de competència","Desistiment","Caducitat automàtica"],0,"La delegació de competències és una tècnica prevista a la Llei 40/2015."],
      ["Quin d'aquests requisits es vincula al dany indemnitzable en la responsabilitat patrimonial?",["Qualsevol dany que s'hagi de suportar jurídicament","Dany efectiu, avaluable econòmicament i individualitzat","Només danys intencionats","Només danys contractuals"],1,"Entre els requisits hi ha que el dany sigui efectiu, avaluable econòmicament i individualitzat."]
    ],
    "4":[
      ["Quin és l'objecte de la Llei orgànica 4/2015?",["La protecció de la seguretat ciutadana","Les eleccions municipals","La contractació pública","La protecció civil exclusivament"],0,"La Llei orgànica 4/2015 té per objecte la protecció de la seguretat ciutadana."],
      ["L'actuació policial en matèria de seguretat ciutadana ha de respectar:",["Només les instruccions internes","Els principis de legalitat, proporcionalitat i no-discriminació, entre d'altres","Exclusivament la conveniència","La voluntat del denunciant"],1,"Les actuacions s'han d'ajustar als principis i garanties previstos per la llei i la resta de l'ordenament."],
      ["Quin criteri ha de regir les mesures d'intervenció policial?",["La màxima intensitat en tots els casos","La proporcionalitat segons les circumstàncies i el marc legal","La decisió del particular","La mesura més restrictiva automàticament"],1,"La intervenció ha de respectar la proporcionalitat i les garanties legals aplicables."],
      ["La identificació de persones en l'àmbit de la seguretat ciutadana:",["Es pot fer sense pressupòsit legal","S'ajusta als supòsits, finalitats i garanties establerts legalment","Permet retenir indefinidament","Sempre equival a una detenció penal"],1,"La identificació s'ha de practicar d'acord amb els supòsits i garanties que preveu la normativa."],
      ["Què s'ha de tenir present en imposar una sanció administrativa?",["La tipificació legal i les garanties del procediment","Només la percepció de l'agent","Que no cal motivar la decisió","Que les sancions es creen per instrucció interna"],0,"La potestat sancionadora està sotmesa als principis de legalitat, tipicitat, proporcionalitat i procediment."]
    ],
    "16":[
      ["Quina norma regula específicament les policies locals a Catalunya?",["Llei 16/1991, de 10 de juliol","Llei orgànica 4/2015","Llei 39/2015","Reial decret legislatiu 6/2015"],0,"La Llei 16/1991, de 10 de juliol, regula les policies locals de Catalunya. Consulta el text vigent al Portal Jurídic de Catalunya."],
      ["Quin és un àmbit d'actuació de les policies locals previst a la Llei 16/1991?",["Exercir funcions de policia judicial en els termes legals","Aprovar lleis autonòmiques","Dirigir els jutjats de pau","Imposar penes privatives de llibertat"],0,"La normativa atribueix funcions de policia judicial en els termes establerts per l'ordenament jurídic i la coordinació policial."],
      ["En relació amb la policia local, qui exerceix el comandament superior del cos en l'àmbit municipal d'acord amb el marc legal?",["L'alcalde o alcaldessa, sens perjudici de les delegacions legalment possibles","El jutjat de guàrdia","El delegat del Govern sempre","El cap de la policia autonòmica"],0,"El comandament de la policia local s'insereix en l'organització municipal i s'ha d'interpretar d'acord amb la Llei 16/1991 i la normativa de règim local."],
      ["Les policies locals de Catalunya formen part de:",["Els cossos de seguretat d'àmbit local","L'Administració de justícia","Les Forces Armades","Els serveis penitenciaris"],0,"Les policies locals són cossos de seguretat d'àmbit local, amb les funcions i principis que estableix la legislació aplicable."],
      ["L'actuació de les policies locals s'ha d'ajustar:",["Als principis bàsics d'actuació de la normativa de forces i cossos de seguretat","Només a les ordres verbals de qualsevol autoritat","A criteris diferents per a cada agent","Exclusivament a les ordenances municipals"],0,"Els principis bàsics d'actuació inclouen el respecte a la Constitució i a la llei, la neutralitat, la integritat i la proporcionalitat. Cal contrastar cada supòsit amb la normativa vigent."],
      ["Quina actuació de trànsit correspon habitualment a la policia local dins del nucli urbà?",["Ordenar, senyalitzar i dirigir el trànsit d'acord amb les normes de circulació","Expedir permisos de conduir","Aprovar el reglament general de circulació","Gestionar exclusivament les autopistes estatals"],0,"La Llei 16/1991 inclou entre les funcions de la policia local ordenar, senyalitzar i dirigir el trànsit en el nucli urbà, d'acord amb les normes de circulació."],
      ["En quin àmbit territorial actua ordinàriament una policia local?",["Al terme municipal corresponent","A tot Catalunya sense cap condició","Només a les dependències municipals","A tot l'Estat"],0,"L'àmbit ordinari d'actuació és el territori del municipi corresponent. Les actuacions fora d'aquest àmbit estan subjectes a supòsits i autoritzacions previstos legalment."],
      ["Què han de fer les policies locals respecte dels accidents de circulació al nucli urbà?",["Poden instruir atestats i comunicar les actuacions als cossos competents","Només poden fer fotografies","No poden intervenir-hi","Han de remetre sempre el cas a una empresa privada"],0,"La normativa atribueix la instrucció d'atestats per accidents de circulació esdevinguts dins el nucli urbà, amb comunicació de les actuacions als cossos competents."],
      ["Quina funció correspon a la policia administrativa local?",["Vetllar pel compliment de les ordenances i disposicions municipals aplicables","Modificar ordenances sense acord municipal","Resoldre recursos judicials","Aprovar sancions penals"],0,"La policia local exerceix funcions de policia administrativa per assegurar el compliment de les ordenances, bans i altres disposicions municipals, d'acord amb la normativa."],
      ["Quina actuació s'inclou en la prevenció del delicte?",["Fer diligències de prevenció i comunicar-les als cossos competents quan correspongui","Investigar qualsevol delicte sense límits territorials ni legals","Substituir el ministeri fiscal","Imposar penes privatives de llibertat"],0,"La Llei 16/1991 inclou diligències de prevenció i actuacions destinades a evitar actes delictuosos, amb la comunicació corresponent."],
      ["Quan poden actuar fora del seu terme municipal?",["En situacions d'emergència i amb l'autorització prèvia de les autoritats competents, segons la informació oficial","Sempre que ho decideixi individualment un agent","Mai, en cap circumstància","Quan ho demani qualsevol particular, sense més requisits"],0,"El Departament d'Interior indica que l'actuació fora de l'àmbit territorial municipal és possible en situacions d'emergència i amb autorització prèvia de les autoritats competents."],
      ["Quina actuació s'associa a la policia local en protecció civil?",["Auxiliar en accidents, catàstrofes i calamitats públiques en els termes legals","Declarar unilateralment l'estat d'alarma","Dirigir els bombers en tots els supòsits","Substituir els serveis sanitaris"],0,"Entre les funcions policials locals hi ha prestar auxili en accidents, catàstrofes i calamitats públiques i participar en plans de protecció civil d'acord amb la llei."],
      ["Quin és un àmbit d'actuació reconegut de les policies locals a Catalunya?",["Policia administrativa","Control de fronteres internacionals","Defensa militar","Expedició de passaports"],0,"El Departament d'Interior identifica, entre altres, els àmbits de trànsit, seguretat ciutadana, policia administrativa, assistencial i judicial."],
      ["Quina tasca de cooperació pot correspondre a les policies locals?",["Col·laborar amb altres cossos policials en els supòsits previstos legalment","Assumir automàticament totes les competències dels Mossos d'Esquadra","Donar ordres a qualsevol cos policial fora del municipi","Substituir els jutjats en investigacions"],0,"La normativa preveu funcions de col·laboració i cooperació amb altres forces i cossos de seguretat en els supòsits legalment establerts."],
      ["Quina naturalesa tenen les policies locals segons l'article 2.1?",["Instituts armats de naturalesa civil, amb estructura i organització jerarquitzades","Cossos militars dependents de la Generalitat","Serveis administratius sense caràcter policial","Unitats judicials dependents dels tribunals"],0,"Article 2.1 de la Llei 16/1991: les policies locals són instituts armats de naturalesa civil amb estructura i organització jerarquitzades."],
      ["Com es pot denominar específicament un cos de policia local per raons de tradició històrica?",["Policia municipal o guàrdia urbana, si ho acorda la corporació local","Guàrdia civil municipal en tots els municipis","Policia judicial municipal exclusivament","Cos autonòmic de seguretat"],0,"Article 2.3: per raons de tradició històrica, la corporació local pot acordar la denominació de policia municipal o guàrdia urbana."],
      ["Quina condició es preveu per crear policia local en un municipi de menys de 10.000 habitants segons l'article 3.2?",["Acord per majoria absoluta del nombre legal de membres de la corporació i autorització del conseller competent, amb informe previ de la Comissió","Acord simple de la junta de govern, sense autorització","Autorització exclusiva del Ministeri de l'Interior","Consulta popular vinculant obligatòria"],0,"Article 3.2 de la Llei 16/1991. Cal tenir present la redacció vigent i la denominació actual dels òrgans competents."],
      ["Qui exerceix el comandament immediat de la policia local?",["El cap del cos","El ple municipal","El jutge degà","La Comissió de Coordinació"],0,"Article 4.3: el comandament immediat correspon al cap del cos."],
      ["Pot l'alcalde delegar les atribucions de comandament de la policia local?",["Sí, d'acord amb la normativa vigent","No, en cap cas","Només en el ple municipal","Només en un jutge"],0,"Article 4.2: l'alcalde exerceix el comandament i pot delegar les atribucions corresponents d'acord amb la normativa vigent."],
      ["Què exigeix l'article 5 per actuar fora del terme municipal?",["Una situació d'emergència i autorització prèvia de les autoritats competents","Una petició verbal de qualsevol ciutadà","Que l'agent estigui fora de servei","Cap condició si hi ha manca de personal"],0,"Article 5.2: l'actuació fora de l'àmbit territorial municipal només és possible en situacions d'emergència i amb autorització prèvia de les autoritats competents."],
      ["Què han de fer els agents abans de prendre possessió del càrrec?",["Jurar o prometre acatar la Constitució i respectar i observar l'Estatut d'autonomia","Jurar fidelitat a un partit polític","Aprovar una ordenança municipal","Sol·licitar autorització judicial individual"],0,"Article 6 de la Llei 16/1991: jurament o promesa d'acatar la Constitució i respectar i observar l'Estatut d'autonomia."],
      ["Quan tenen els vigilants municipals la condició d'agents de l'autoritat segons l'article 7.2?",["Quan actuen identificats i en les funcions pròpies, i el municipi no disposa de policia local","Sempre, fins i tot quan fan funcions privades","Només quan porten arma de foc","Mai, en cap supòsit"],0,"Article 7.2: la condició està subjecta a requisits, entre els quals actuar degudament identificats en les funcions pròpies i que el municipi no disposi de policia local."],
      ["Poden els vigilants municipals regulats a l'article 1.2 portar armes de foc?",["No","Sí, si ho autoritza qualsevol regidor","Sí, sempre que estiguin uniformats","Només durant els torns nocturns"],0,"Article 8.3: els vigilants a què es refereix l'article 1.2 no poden portar armes de foc."],
      ["Qui determina motivadament les circumstàncies i els serveis en què els policies locals no portaran armes de foc?",["L'alcalde","El cap de cada torn sense cap límit","El jutjat de guàrdia","La persona denunciant"],0,"Article 8.2: correspon a l'alcalde determinar-ho de forma motivada."],
      ["Per a què es pot utilitzar l'uniforme reglamentari?",["Només per al compliment del servei","Per a qualsevol activitat privada","Només per a actes institucionals","Per prestar serveis de seguretat privada"],0,"Article 9.1: l'uniforme reglamentari només pot utilitzar-se per al compliment del servei."],
      ["Què han de portar els policies locals quan estan autoritzats a prestar un servei sense uniforme?",["La documentació acreditativa de la seva condició","Necessàriament una arma llarga visible","Una autorització judicial en tots els casos","Cap identificació professional"],0,"Article 9.2: qui actua sense uniforme reglamentari ha de portar la documentació acreditativa de la seva condició."],
      ["Pot una ordre jeràrquica justificar l'execució d'un acte manifestament delictiu?",["No; l'obediència deguda no empara actes manifestament delictius o contraris a la Constitució, l'Estatut o les lleis","Sí, sempre que l'ordre sigui escrita","Sí, si ho ordena un superior jeràrquic","Només si l'acte passa durant una emergència"],0,"Article 10.1, principi d'adequació a l'ordenament jurídic: l'obediència deguda no empara actes manifestament delictius o contraris a les normes indicades."],
      ["Quin tracte han de dispensar els policies locals a la ciutadania?",["Un tracte correcte i acurat, amb auxili i protecció quan les circumstàncies ho aconsellin o siguin requerits","Un tracte diferent segons l'opinió política","Només informació si ho ordena un jutge","Cap informació sobre la finalitat de les intervencions"],0,"Article 10.1: s'exigeix un tracte correcte i esmerat i, tant com sigui possible, informació sobre les causes i la finalitat de les intervencions."],
      ["Quan es poden utilitzar les armes de foc segons els principis de l'article 10?",["En situacions de risc racionalment greu per a la vida o integritat física, o de greu risc per a la seguretat ciutadana, amb els principis aplicables","Sempre que una persona no obeeixi immediatament","Per evitar qualsevol infracció administrativa","Només quan ho demani un particular"],0,"Article 10.1: l'ús d'armes està limitat als supòsits de risc greu que estableix la llei i queda subjecte als principis de congruència, oportunitat i proporcionalitat."],
      ["Quin deure professional estableix la Llei 16/1991 sobre la informació coneguda durant el servei?",["Guardar secret professional, amb les excepcions legals","Publicar-la sempre en xarxes socials","Comunicar-la a qualsevol particular que la demani","Destruir-la en acabar el torn"],0,"Article 10.1: els policies locals han de guardar rigorós secret sobre la informació coneguda per raó o ocasió del servei, llevat dels supòsits legals."],
      ["Segons l’article 10, quan es pot justificar l’ús de les armes de foc?",["Quan existeix un risc racionalment greu per a la vida o integritat pròpia o de terceres persones, o un greu risc per a la seguretat ciutadana","Sempre que una persona no obeeixi una ordre","Per evitar qualsevol fugida, sense valorar el risc","Només quan ho autoritzi prèviament un jutge"],0,"Article 10.1, segon: l’ús d’armes queda limitat a situacions de risc racionalment greu i s’ha de regir pels principis de congruència, oportunitat i proporcionalitat. Font: BOE, Llei 16/1991."],
      ["Quin principi limita l’obediència jeràrquica dels agents?",["No s’han d’obeir ordres que constitueixin manifestament delicte o siguin contràries a la Constitució, l’Estatut o les lleis","Cal obeir sempre qualsevol ordre, sigui quin sigui el contingut","Només es poden desobeir ordres escrites","L’agent pot decidir lliurement si compleix les ordres legals"],0,"Article 10.1, primer, lletra d): la subordinació no empara ordres manifestament delictives o contràries a l’ordenament indicat."],
      ["En efectuar una detenció, quin deure específic recull l’article 10?",["Identificar-se degudament com a agent","Esperar a arribar a comissaria per identificar-se","Informar únicament els familiars","No comunicar mai la causa de la intervenció"],0,"Article 10.1, tercer, lletra a): l’agent s’ha d’identificar degudament en el moment d’efectuar la detenció."],
      ["Quin deure tenen els agents respecte de les persones detingudes o sota custòdia?",["Vetllar per la seva vida i integritat física i respectar els seus drets, honor i dignitat","Restringir-ne els drets sense cap límit","Permetre que terceres persones les interroguin lliurement","Retardar sempre els tràmits fins al canvi de torn"],0,"Article 10.1, tercer, lletra b), de la Llei 16/1991."],
      ["Què estableix la Llei 16/1991 sobre la dedicació professional?",["Cal intervenir en defensa de la llei i la seguretat ciutadana en qualsevol moment i lloc, tant si s’està de servei com si no","Només s’hi ha d’intervenir durant el torn assignat","Fora de servei només es pot actuar amb autorització de l’alcaldia","La intervenció fora de servei està sempre prohibida"],0,"Article 10.1, quart: la llei estableix el deure d’intervenir en defensa de la llei i la seguretat ciutadana, amb els límits que resultin de l’ordenament jurídic."],
      ["Quina responsabilitat preveu l’article 10.2 per als policies locals?",["Responsabilitat personal i directa pels actes o omissions que vulnerin normes i principis aplicables, sens perjudici de la responsabilitat patrimonial de l’Administració","Només responsabilitat política de l’alcaldia","Cap responsabilitat individual si hi ha una ordre superior","Exclusivament responsabilitat civil davant de particulars"],0,"Article 10.2 de la Llei 16/1991: responsabilitat personal i directa de l’agent, sense perjudici de la que pugui correspondre a l’Administració."],
      ["Un accident de circulació té lloc dins del nucli urbà. Quina funció atribueix l’article 11 a la policia local?",["Instruir l’atestat i comunicar les actuacions als cossos de seguretat competents","Imposar directament una pena penal","Traslladar sempre la investigació a una empresa privada","Actuar només si hi ha lesions greus"],0,"Article 11.c): la policia local instrueix atestats per accidents de circulació dins del nucli urbà i comunica les actuacions als cossos competents."],
      ["La policia local rep un requeriment per cooperar en un conflicte privat. Quina resposta encaixa amb l’article 11?",["Pot cooperar en la resolució del conflicte quan sigui requerida per fer-ho","Ha de resoldre’l com si fos un tribunal","Només hi pot intervenir si hi ha una ordre judicial","No pot intervenir mai en conflictes privats"],0,"Article 11.h): cooperar en la resolució de conflictes privats quan sigui requerida per fer-ho."],
      ["Quina funció de policia local està expressament prevista en matèria ambiental?",["Vetllar pel compliment de la normativa vigent sobre medi ambient i protecció de l’entorn","Aprovar autoritzacions ambientals autonòmiques en tots els casos","Substituir la inspecció de tots els organismes ambientals","Dictar normes ambientals amb rang de llei"],0,"Article 11.k) de la Llei 16/1991."],
      ["Quan han de col·laborar les policies locals amb altres forces de seguretat en manifestacions i grans concentracions?",["Quan siguin requerides per fer-ho, en els termes de l’article 11","Sempre assumint-ne el comandament","Només si ho demana un particular","Mai, perquè és una competència exclosa"],0,"Article 11.g): col·laboració amb les forces i cossos de seguretat de l’Estat i la policia autonòmica quan siguin requerides."],
      ["En funcions de policia judicial, quan poden practicar-se les primeres diligències de prevenció i custòdia?",["Per iniciativa pròpia o a requeriment de l’autoritat judicial, del Ministeri Fiscal o dels superiors jeràrquics, en els termes legals","Només després d’una sentència ferma","Exclusivament per ordre escrita de l’alcalde","Només quan ho demani la persona detinguda"],0,"Article 12.1.b): regula les primeres diligències de prevenció i custòdia de detinguts i objectes relacionats amb el delicte."],
      ["A qui s’han de comunicar les actuacions de policia judicial en els terminis legals?",["A l’autoritat judicial o al Ministeri Fiscal, d’acord amb la normativa vigent","Només a l’alcalde","Només als mitjans de comunicació","A qualsevol persona que ho sol·liciti"],0,"Article 12.1.b): les actuacions s’han de comunicar a l’autoritat judicial o al Ministeri Fiscal en els terminis legalment establerts."],
      ["Què significa coordinació de les policies locals segons l’article 14?",["Establir mitjans i sistemes de relació per possibilitar una acció conjunta i integrar les actuacions en el sistema de seguretat ciutadana","Unificar tots els ajuntaments en una única administració","Substituir les competències municipals per les estatals","Fer que tots els cossos tinguin necessàriament la mateixa plantilla"],0,"Article 14 de la Llei 16/1991: la coordinació facilita l’acció conjunta i la integració de les actuacions en el sistema de seguretat ciutadana."],
      ["Quina d’aquestes matèries pot incloure la coordinació prevista a l’article 15?",["Homogeneïtzació de mitjans tècnics i elements comuns, i establiment d’un sistema d’informació recíproca","Aprovació dels pressupostos de cada ajuntament","Nomenament directe de tots els alcaldes","Direcció ordinària de cada torn policial municipal"],0,"Article 15.1.a) i b): homogeneïtzació de mitjans tècnics i instruments d’informació recíproca."],
      ["Quin límit estableix l’article 15.2 a les funcions de coordinació?",["S’han de respectar l’autonomia local i les competències municipals en matèria de policia local","La coordinació elimina tota autonomia municipal","Les funcions de coordinació només es poden exercir amb autorització judicial","La coordinació pot modificar qualsevol ordenança municipal directament"],0,"Article 15.2 de la Llei 16/1991: la coordinació ha de respectar l’autonomia local i les competències municipals."],
      ["Quina documentació han de trametre i fer pública anualment les corporacions locals amb policia local o vigilants, segons l’article 20?",["La memòria dels serveis de l’any anterior i la dotació de recursos humans i materials","Només la relació de sancions de trànsit","Exclusivament el pressupost municipal","La llista de totes les persones identificades al municipi"],0,"Article 20.1: en el primer trimestre de cada any s’ha d’enviar al departament competent i fer pública la memòria dels serveis prestats l’any anterior i la dotació de recursos humans i materials."] ,
    ],
    trafic:[
      ["Quina és la norma estatal bàsica en matèria de trànsit i seguretat viària?",["Reial decret legislatiu 6/2015","Llei 39/2015 exclusivament","Llei orgànica 4/2015 exclusivament","Codi civil"],0,"El Reial decret legislatiu 6/2015 aprova el text refós de la Llei sobre trànsit, circulació de vehicles de motor i seguretat viària."],
      ["Quina obligació general tenen els usuaris de la via?",["No tenir en compte altres usuaris","No entorpir indegudament la circulació ni causar perill o dany","Respectar només senyals verticals","Aturar-se davant de qualsevol vehicle estacionat"],1,"Els usuaris de la via han d'evitar causar perill, perjudicis o molèsties innecessàries."],
      ["Què ha de fer un conductor davant la llum vermella fixa d'un semàfor?",["Accelerar si no veu vehicles","Aturar-se al lloc reglamentari","Continuar si gira a la dreta en tots els casos","Cedir el pas només als vianants"],1,"La llum vermella fixa prohibeix el pas i obliga a aturar-se en el lloc reglamentari."],
      ["Què obliga a fer un senyal de STOP?",["Reduir la velocitat i continuar si no hi ha ningú","Aturar-se i cedir el pas segons les normes aplicables","Aturar-se només si hi ha un agent","Cedir el pas només als vehicles pesants"],1,"El senyal STOP obliga a aturar-se i cedir el pas conforme a les normes de prioritat."],
      ["L'ús del cinturó de seguretat:",["Només és obligatori en autopistes","És obligatori segons la normativa vigent, amb les excepcions previstes","Només és obligatori per al conductor","Depèn de l'asseguradora"],1,"La normativa estableix l'obligació d'utilitzar els cinturons i preveu excepcions concretes."]
    ]
  };
  const HISTORY_KEY = "oposiprep-history-v1";
  function loadHistory(){
    try {
      const saved = JSON.parse(localStorage.getItem(HISTORY_KEY) || "[]");
      return Array.isArray(saved) ? saved.filter(x => x && typeof x.correct === "number" && typeof x.total === "number" && typeof x.percent === "number").slice(0,50) : [];
    } catch (_) { return []; }
  }
  const state = {opposition:"policia",law:"constitucio",count:15,questions:[],index:0,answers:{},checked:{},history:loadHistory()};
  const dialog = $("#messageDialog");
  function message(title,body){$("#dialogTitle").textContent=title;$("#dialogMessage").textContent=body;if(dialog.showModal)dialog.showModal();else alert(title+"\n"+body);}
  function refreshStats(){
    const tests=state.history.length;
    const total=state.history.reduce((n,x)=>n+x.total,0);
    const hits=state.history.reduce((n,x)=>n+x.correct,0);
    $("#statTests").textContent=tests;
    $("#statAccuracy").textContent=total ? Math.round(hits/total*100)+"%" : "—";
    $("#statBest").textContent=tests ? Math.max(...state.history.map(x=>x.percent))+"%" : "—";
    const hist=$(".history-card");
    if(tests){
      const last=state.history[0];
      hist.querySelector("strong").textContent=tests+" test"+(tests===1?" completat":"s completats");
      hist.querySelector("p").textContent=last.date+" · "+last.law+" · "+last.percent+"% d'encerts";
      hist.querySelector(".history-icon").textContent="✓";
    } else {
      hist.querySelector("strong").textContent="Historial de pràctica";
      hist.querySelector("p").textContent="Quan completis un test, aquí veuràs els teus resultats.";
      hist.querySelector(".history-icon").textContent="↗";
    }
  }
  function shuffle(list){const a=[...list];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
  $$(".opposition-card").forEach(card=>card.addEventListener("click",()=>{$$(".opposition-card").forEach(c=>c.classList.toggle("selected",c===card));state.opposition=card.dataset.opposition;}));
  $$(".law-item").forEach(item=>item.addEventListener("click",()=>{$$(".law-item").forEach(c=>c.classList.toggle("selected",c===item));state.law=item.dataset.law;}));
  $("#lawSearch").addEventListener("input",e=>{const q=e.target.value.toLocaleLowerCase("ca").trim();$$(".law-item").forEach(item=>item.hidden=!item.textContent.toLocaleLowerCase("ca").includes(q));});
  $$(".count-option").forEach(btn=>btn.addEventListener("click",()=>{if(btn.classList.contains("premium-option")){message("Més preguntes amb Premium","Els tests de 30 i 50 preguntes formaran part de la subscripció. En aquesta demostració pots provar un test de 10 o 15 preguntes.");return;}$$(".count-option").forEach(b=>b.classList.toggle("active",b===btn));state.count=Number(btn.dataset.count);}));
  const premium=()=>message("OposiPrep Premium","La subscripció inclourà tests de diverses normes, sessions més llargues i seguiment ampliat. Els pagaments encara no estan activats: cal connectar un backend segur i un proveïdor de pagaments.");
  $("#upgradeTop").addEventListener("click",premium);$("#upgradeBottom").addEventListener("click",premium);$("#multiToggle").addEventListener("click",premium);$("#closeDialog").addEventListener("click",()=>dialog.close());
  function resetQuizBody(){
    $(".quiz-body").innerHTML='<p class="eyebrow" id="quizLawLabel"></p><h1 id="quizTitle"></h1><p class="quiz-instruction">Selecciona una única resposta.</p><div id="answerOptions" class="answer-options"></div><div id="answerFeedback" class="answer-feedback" hidden></div><div class="quiz-actions"><button class="button button-outline" id="prevQuestion">← Anterior</button><button class="button button-primary" id="nextQuestion">Comprovar resposta →</button></div>';
    $("#prevQuestion").addEventListener("click",previous);$("#nextQuestion").addEventListener("click",next);
  }
  function start(){
    if($("#lawText").value.trim()){message("Generació automàtica pendent","El text que enganxis no s'envia a cap servidor en aquesta demostració. Per generar preguntes a partir d'una norma cal connectar un servei d'IA al backend; aquesta funció encara no està activada.");return;}
    resetQuizBody();
    state.questions=shuffle(banks[state.law]||banks.constitucio).slice(0,Math.min(state.count,(banks[state.law]||banks.constitucio).length));state.index=0;state.answers={};state.checked={};
    $("#quizOverlay").hidden=false;document.body.style.overflow="hidden";render();
    if(state.count>state.questions.length)message("Mode demostració","Aquesta norma disposa de "+state.questions.length+" preguntes de mostra. El banc complet de preguntes encara s'ha d'ampliar.");
  }
  function render(){
    const q=state.questions[state.index],total=state.questions.length;
    $("#quizCounter").textContent="PREGUNTA "+(state.index+1)+" DE "+total;$("#quizPercent").textContent=Math.round((state.index+1)/total*100)+"%";$("#quizProgressBar").style.width=((state.index+1)/total*100)+"%";
    $("#quizLawLabel").textContent=names[state.law].toLocaleUpperCase("ca");$("#quizTitle").textContent=q[0];$("#answerFeedback").hidden=true;$("#answerFeedback").textContent="";
    const list=$("#answerOptions");list.replaceChildren();
    q[1].forEach((answer,i)=>{const b=document.createElement("button");b.type="button";b.className="answer-option";const letter=document.createElement("span");letter.className="answer-letter";letter.textContent=String.fromCharCode(65+i);const text=document.createElement("span");text.textContent=answer;b.append(letter,text);if(state.answers[state.index]===i)b.classList.add("chosen");if(state.checked[state.index]){b.disabled=true;if(i===q[2])b.classList.add("correct");else if(state.answers[state.index]===i)b.classList.add("wrong");}b.addEventListener("click",()=>{if(state.checked[state.index])return;state.answers[state.index]=i;$$(".answer-option",list).forEach(x=>x.classList.remove("chosen"));b.classList.add("chosen");});list.append(b);});
    $("#prevQuestion").disabled=state.index===0;$("#prevQuestion").style.opacity=state.index===0?".45":"1";$("#nextQuestion").textContent=state.checked[state.index]?(state.index===total-1?"Veure resultats →":"Següent pregunta →"):"Comprovar resposta →";
    if(state.checked[state.index]){const f=$("#answerFeedback");f.hidden=false;f.textContent=(state.answers[state.index]===q[2]?"Correcte. ":"Incorrecte. La resposta correcta és "+String.fromCharCode(65+q[2])+". ")+q[3];}
  }
  function results(){
    const total=state.questions.length,correct=state.questions.filter((q,i)=>state.answers[i]===q[2]).length,percent=Math.round(correct/total*100);
    state.history.unshift({date:new Date().toLocaleDateString("ca-ES"),law:names[state.law],correct,total,percent});
    state.history=state.history.slice(0,50);
    try { localStorage.setItem(HISTORY_KEY, JSON.stringify(state.history)); } catch (_) {}
    refreshStats();
    $("#quizCounter").textContent="TEST COMPLETAT";$("#quizPercent").textContent="100%";$("#quizProgressBar").style.width="100%";$("#quizLawLabel").textContent="RESULTAT · "+names[state.law].toLocaleUpperCase("ca");$("#quizTitle").textContent="Així ha anat aquesta sessió";$(".quiz-instruction").textContent="Has completat totes les preguntes.";
    $("#answerOptions").replaceChildren();$("#answerFeedback").hidden=true;
    const score=document.createElement("div");score.className="result-score";score.textContent=percent+"%";
    const summary=document.createElement("p");summary.className="result-message";summary.textContent=correct+" de "+total+" respostes correctes · "+(total-correct)+" per revisar.";
    const encouragement=document.createElement("p");encouragement.className="result-message";encouragement.textContent=percent>=80?"Molt bona feina! Continua repassant per consolidar els coneixements.":percent>=60?"Vas pel bon camí. Repassa les preguntes fallades i torna-ho a provar.":"Cada test és una oportunitat per millorar. Revisa les explicacions i practica de nou.";
    const review=document.createElement("div");review.className="result-review";const heading=document.createElement("h3");heading.textContent="Repàs de les respostes";review.append(heading);
    state.questions.forEach((q,i)=>{const row=document.createElement("div");row.className="review-item";const title=document.createElement("strong");title.textContent=(i+1)+". "+q[0];const detail=document.createElement("span");detail.textContent=(state.answers[i]===q[2]?"Correcte. ":"Incorrecte. Resposta correcta: "+String.fromCharCode(65+q[2])+". ")+q[1][q[2]]+" — "+q[3];row.append(title,detail);review.append(row);});
    const body=$(".quiz-body");body.append(score,summary,encouragement,review);
    const actions=$(".quiz-actions");actions.replaceChildren();const exit=document.createElement("button");exit.className="button button-outline";exit.textContent="Tornar a l'inici";exit.addEventListener("click",close);const retry=document.createElement("button");retry.className="button button-primary";retry.textContent="Repetir test →";retry.addEventListener("click",start);actions.append(exit,retry);
    refreshStats();
  }
  function close(){ $("#quizOverlay").hidden=true;document.body.style.overflow="";resetQuizBody();}
  function previous(){if(state.index>0){state.index--;render();}}
  function next(){if(!state.checked[state.index]){if(state.answers[state.index]===undefined){message("Tria una resposta","Selecciona una de les quatre opcions abans de continuar.");return;}state.checked[state.index]=true;render();return;}if(state.index<state.questions.length-1){state.index++;render();}else results();}
  $("#startTest").addEventListener("click",start);$("#prevQuestion").addEventListener("click",previous);$("#nextQuestion").addEventListener("click",next);
  $("#exitQuiz").addEventListener("click",()=>{if(confirm("Vols sortir del test? Perdràs el progrés d'aquesta sessió."))close();});
  refreshStats();
})();