(() => {
  "use strict";
  const $ = (s, root = document) => root.querySelector(s);
  const $$ = (s, root = document) => [...root.querySelectorAll(s)];
  const names = { constitucio:"Constitució espanyola", "39":"Llei 39/2015", "40":"Llei 40/2015", "4":"Llei orgànica 4/2015", "16":"Llei 16/1991 de les policies locals", trafic:"Normativa de trànsit" };
  const banks = {
    constitucio:[
      ["Segons la Constitució espanyola, on resideix la sobirania nacional?",["A les Corts Generals","En el poble espanyol","En el cap de l'Estat","En el Govern"],1,"L'article 1.2 estableix que la sobirania nacional resideix en el poble espanyol, del qual emanen els poders de l'Estat."],
      ["Quin article reconeix la igualtat davant la llei?",["Article 9","Article 14","Article 24","Article 30"],1,"L'article 14 proclama la igualtat davant la llei i prohibeix la discriminació pels motius que enumera."],
      ["Quina és la forma política de l'Estat espanyol?",["República parlamentària","Monarquia absoluta","Monarquia parlamentària","Estat confederal"],2,"L'article 1.3 estableix que la forma política de l'Estat espanyol és la monarquia parlamentària."],
      ["Quin dret protegeix l'article 18.1?",["El dret de reunió","El dret a l'educació","L'honor, la intimitat personal i familiar i la pròpia imatge","La llibertat sindical"],2,"L'article 18.1 garanteix el dret a l'honor, a la intimitat personal i familiar i a la pròpia imatge."],
      ["Qui exerceix la potestat legislativa de l'Estat?",["El Govern exclusivament","Les Corts Generals","El Tribunal Constitucional","El Consell General del Poder Judicial"],1,"Les Corts Generals exerceixen la potestat legislativa, aproven els pressupostos i controlen l'acció del Govern."]
,
      ["Quins valors superiors proclama l’article 1.1 de la Constitució?",["Llibertat, justícia, igualtat i pluralisme polític","Unitat, disciplina, seguretat i eficàcia","Legalitat, jerarquia, descentralització i coordinació","Solidaritat, propietat, ordre i estabilitat"],0,"L’article 1.1 proclama la llibertat, la justícia, la igualtat i el pluralisme polític com a valors superiors."],
      ["Quin principi garanteix l’article 9.3 de la Constitució?",["La retroactivitat general de les sancions desfavorables","La publicitat de les normes i la seguretat jurídica, entre altres garanties","La llibertat absoluta dels poders públics","La supressió del control judicial"],1,"L’article 9.3 garanteix, entre altres principis, la legalitat, la jerarquia normativa, la publicitat de les normes, la seguretat jurídica i la interdicció de l’arbitrarietat."],
      ["Quin dret reconeix l’article 17.1?",["El dret a l’educació gratuïta universitària","El dret a la llibertat i a la seguretat","El dret de petició col·lectiva exclusivament","El dret a la negociació col·lectiva"],1,"L’article 17.1 reconeix que tota persona té dret a la llibertat i a la seguretat."],
      ["Quina garantia estableix l’article 17.2 sobre la detenció preventiva?",["Pot durar fins a set dies sense control judicial","No pot durar més del temps estrictament necessari i, en tot cas, dins del termini màxim constitucional","Sempre dura exactament 72 hores","La determina exclusivament l’autoritat municipal"],1,"L’article 17.2 estableix que la detenció preventiva no pot durar més del temps estrictament necessari i fixa el límit màxim de 72 hores abans de la posada en llibertat o a disposició judicial."],
      ["Quin dret protegeix l’article 19?",["La llibertat de residència i circulació pel territori nacional, en els termes constitucionals","El dret a vaga dels funcionaris en qualsevol circumstància","La inviolabilitat del domicili exclusivament","La llibertat d’empresa sense límits"],0,"L’article 19 reconeix la llibertat de residència i circulació dels espanyols pel territori nacional, amb els límits constitucionals."],
      ["Què exigeix l’article 24.1?",["Que només els funcionaris puguin acudir als tribunals","La tutela judicial efectiva dels drets i interessos legítims, sense indefensió","Que tots els litigis es resolguin administrativament","Que les resolucions judicials no siguin motivades"],1,"L’article 24.1 reconeix el dret a obtenir tutela efectiva dels jutges i tribunals en l’exercici dels drets i interessos legítims, sense indefensió."],
      ["Quin principi regeix la potestat sancionadora administrativa segons l’article 25.1?",["Es poden sancionar conductes no previstes en cap norma","Ningú no pot ser sancionat per accions o omissions que no constitueixin infracció segons la legislació vigent quan es produeixen","Les sancions administratives no necessiten cobertura legal","Les ordenances poden crear penes privatives de llibertat"],1,"L’article 25.1 consagra el principi de legalitat sancionadora: la conducta ha d’estar tipificada prèviament per la legislació vigent."],
      ["Què prohibeix l’article 15 de la Constitució?",["La pena de mort, llevat de l’excepció constitucional prevista per a les lleis penals militars en temps de guerra","Qualsevol privació de llibertat","Tota intervenció policial coercitiva","Qualsevol sanció administrativa"],0,"L’article 15 reconeix el dret a la vida i a la integritat física i moral i aboleix la pena de mort, amb l’excepció constitucional expressa."],
      ["Quina garantia correspon al domicili segons l’article 18.2?",["Pot entrar-hi qualsevol agent sense justificació","És inviolable; l’entrada requereix consentiment o resolució judicial, excepte en cas de delicte flagrant","Només és inviolable durant la nit","La protecció només s’aplica als propietaris"],1,"L’article 18.2 declara inviolable el domicili i regula el consentiment, la resolució judicial i l’excepció del delicte flagrant."],
      ["Quin dret reconeix l’article 21?",["El dret de reunió pacífica i sense armes, amb els requisits constitucionals","El dret a reunir-se sempre sense comunicació en qualsevol espai","El dret a ocupar qualsevol edifici públic","El dret a impedir qualsevol reunió aliena"],0,"L’article 21 reconeix el dret de reunió pacífica i sense armes; per a reunions en llocs de trànsit públic i manifestacions s’aplica el règim de comunicació prèvia."],
      ["Quin òrgan controla la constitucionalitat de les lleis?",["El Tribunal Suprem en tots els casos","El Tribunal Constitucional","El Consell d’Estat","El Congrés dels Diputats"],1,"El Tribunal Constitucional és l’intèrpret suprem de la Constitució i coneix, entre altres assumptes, dels recursos i qüestions d’inconstitucionalitat."],
      ["Qui sanciona i promulga les lleis de l’Estat?",["El president del Congrés","El rei, en els termes previstos a la Constitució","El Tribunal Constitucional","El president del Tribunal Suprem"],1,"L’article 62.a atribueix al rei la sanció i promulgació de les lleis, d’acord amb el procediment constitucional."],
      ["Quina cambra representa el poble espanyol segons l’article 66?",["El Senat exclusivament","Les Corts Generals, formades pel Congrés dels Diputats i el Senat","El Consell General del Poder Judicial","El Govern i les comunitats autònomes"],1,"L’article 66 estableix que les Corts Generals representen el poble espanyol i es componen del Congrés dels Diputats i el Senat."],
      ["Quina és la missió constitucional de les Forces i Cossos de Seguretat segons l’article 104.1?",["Garantir la sobirania parlamentària i aprovar lleis","Protegir el lliure exercici dels drets i llibertats i garantir la seguretat ciutadana","Dirigir l’Administració de justícia","Exercir la potestat legislativa municipal"],1,"L’article 104.1 encomana a les Forces i Cossos de Seguretat protegir el lliure exercici dels drets i llibertats i garantir la seguretat ciutadana."],
      ["Quin principi estableix l’article 103.1 per a l’Administració pública?",["Actuar amb objectivitat i servir els interessos generals amb eficàcia, jerarquia, descentralització, desconcentració i coordinació, amb submissió a la llei i al dret","Actuar només segons instruccions polítiques particulars","Prioritzar sempre l’interès privat","No estar sotmesa al control judicial"],0,"L’article 103.1 fixa els principis d’actuació de l’Administració pública i la seva submissió plena a la llei i al dret."],
      ["Quin dret reconeix l’article 29?",["El dret de petició individual i col·lectiva per escrit, en la forma i amb els efectes que determini la llei","El dret a dictar resolucions administratives","El dret a no identificar-se mai davant l’autoritat","El dret a suspendre qualsevol procediment"],0,"L’article 29 reconeix el dret de petició individual i col·lectiva per escrit, amb les particularitats constitucionals previstes per als membres de cossos sotmesos a disciplina militar."]
,
      ["Quin és el termini ordinari de mandat del Congrés dels Diputats i del Senat?",["Tres anys","Quatre anys","Cinc anys","Sis anys"],1,"L’article 68.4 fixa en quatre anys el mandat del Congrés i l’article 69.6 estableix també quatre anys per al Senat."],
      ["Quina majoria es requereix, amb caràcter general, per adoptar acords a cada cambra?",["Unanimitat","Majoria absoluta dels membres en tots els casos","Majoria simple dels membres presents, sens perjudici de majories especials","Dues terceres parts sempre"],2,"L’article 79.2 estableix que els acords són vàlids si s’adopten per la majoria dels membres presents, sens perjudici de les majories especials."],
      ["Quin òrgan exerceix la potestat executiva i la potestat reglamentària d’acord amb la Constitució?",["Les Corts Generals","El Govern","El Tribunal Constitucional","El Consell General del Poder Judicial"],1,"L’article 97 estableix que el Govern dirigeix la política interior i exterior, l’Administració civil i militar i la defensa de l’Estat, i exerceix la funció executiva i la potestat reglamentària."],
      ["Quina és la funció del Defensor del Poble?",["Dirigir la policia judicial","Supervisar l’activitat de l’Administració i defensar els drets del títol I, com a alt comissionat de les Corts Generals","Aprovar els pressupostos generals","Resoldre tots els recursos administratius"],1,"L’article 54 configura el Defensor del Poble com a alt comissionat de les Corts Generals per defensar els drets del títol I i supervisar l’activitat administrativa."],
      ["Qui pot interposar un recurs d’inconstitucionalitat segons la Constitució?",["Qualsevol ciutadà sense requisits","El president del Govern, el Defensor del Poble, cinquanta diputats, cinquanta senadors i els òrgans legitimats de les comunitats autònomes en els termes constitucionals","Només el rei","Només els jutges de pau"],1,"L’article 162.1.a enumera els subjectes legitimats per interposar el recurs d’inconstitucionalitat."],
      ["Quin és el principi constitucional de l’actuació judicial?",["Els jutges depenen jeràrquicament del Govern en les seves resolucions","La independència dels jutges i magistrats, sotmesos únicament a l’imperi de la llei","Les sentències poden dictar-se per instruccions polítiques","La jurisdicció és potestat dels ajuntaments"],1,"L’article 117.1 estableix que la justícia emana del poble i s’administra per jutges i magistrats independents, inamovibles, responsables i sotmesos únicament a l’imperi de la llei."],
      ["Quina garantia estableix l’article 120.3?",["Les sentències sempre són secretes","Les sentències han de ser motivades i es pronuncien en audiència pública, amb les excepcions legals","Les sentències no necessiten fonament jurídic","Les sentències les valida l’alcaldia"],1,"L’article 120.3 estableix que les sentències seran sempre motivades i es pronunciaran en audiència pública."],
      ["Quina és la forma política de l’Estat espanyol?",["República federal","Monarquia parlamentària","Monarquia absoluta","Confederació de repúbliques"],1,"L’article 1.3 estableix que la forma política de l’Estat espanyol és la monarquia parlamentària."],
      ["Què estableix l’article 2 de la Constitució?",["El dret de secessió unilateral de qualsevol municipi","La unitat de la nació espanyola i el reconeixement i garantia del dret a l’autonomia de les nacionalitats i regions, així com la solidaritat entre totes","La desaparició de les províncies","La subordinació dels municipis al poder judicial"],1,"L’article 2 combina la unitat de la nació espanyola amb el dret a l’autonomia de nacionalitats i regions i la solidaritat entre elles."],
      ["Quina és la llengua espanyola oficial de l’Estat segons l’article 3.1?",["El català","El castellà, que tots els espanyols tenen el deure de conèixer i el dret d’usar","Totes les llengües autonòmiques en tot el territori amb el mateix règim","Només la llengua que determini cada ajuntament"],1,"L’article 3.1 declara el castellà llengua espanyola oficial de l’Estat i estableix el deure de conèixer-la i el dret d’usar-la."],
      ["Quin dret reconeix l’article 23.2?",["Accedir en condicions d’igualtat a les funcions i càrrecs públics, amb els requisits que assenyalin les lleis","Accedir a qualsevol lloc públic sense procés selectiu","Exercir potestats públiques sense nomenament","Obtenir sempre una plaça fixa"],0,"L’article 23.2 reconeix el dret a accedir en condicions d’igualtat a les funcions i càrrecs públics, amb els requisits legals."],
      ["Quin principi regeix l’organització territorial de l’Estat segons l’article 137?",["Municipis, províncies i comunitats autònomes gaudeixen d’autonomia per gestionar els seus interessos respectius","Tots els municipis depenen directament del Congrés","Les províncies no formen part de l’organització territorial","Les comunitats autònomes no tenen autonomia"],0,"L’article 137 organitza territorialment l’Estat en municipis, províncies i comunitats autònomes, totes amb autonomia per gestionar els seus interessos respectius."],
      ["Quina és la funció del Tribunal de Comptes?",["Controlar exclusivament les actuacions policials","Fiscalitzar els comptes i la gestió econòmica de l’Estat i del sector públic, en els termes constitucionals","Aprovar lleis orgàniques","Nomenar els alcaldes"],1,"L’article 136 configura el Tribunal de Comptes com l’òrgan fiscalitzador suprem dels comptes i de la gestió econòmica de l’Estat i del sector públic."],
      ["Què exigeix la Constitució per regular el desenvolupament dels drets fonamentals i de les llibertats públiques de la secció primera del capítol segon del títol I?",["Una ordenança municipal","Llei orgànica","Un decret d’alcaldia","Un reglament intern policial"],1,"L’article 81.1 reserva a llei orgànica el desenvolupament dels drets fonamentals i les llibertats públiques, entre altres matèries."],
      ["Quin dret protegeix l’article 18.3?",["El secret de les comunicacions, especialment les postals, telegràfiques i telefòniques, llevat de resolució judicial","La publicació de totes les comunicacions privades","La consulta lliure de qualsevol missatge","El dret a interceptar comunicacions sense control"],0,"L’article 18.3 garanteix el secret de les comunicacions, amb l’excepció de resolució judicial."]
    ],
    "39":[
      ["Quina matèria regula principalment la Llei 39/2015?",["El règim del personal laboral privat","El procediment administratiu comú de les administracions públiques","L'organització del poder judicial","El règim electoral general"],1,"La Llei 39/2015 regula el procediment administratiu comú de les administracions públiques."],
      ["Com es computen, amb caràcter general, els terminis assenyalats per dies?",["Sempre com a dies naturals","Com a dies hàbils, llevat que s'indiquin dies naturals","Només de dilluns a dijous","Com a dies naturals, excepte a l'agost"],1,"La regla general és el còmput en dies hàbils: s'exclouen dissabtes, diumenges i festius, llevat que s'estableixi que són naturals."],
      ["Quin és un dret de les persones interessades en un procediment?",["Exigir una resolució favorable","Conèixer l'estat de tramitació del procediment","Ometre sempre qualsevol identificació","Escollir el sentit de la resolució"],1,"La Llei reconeix el dret de les persones interessades a conèixer l'estat de tramitació del procediment."],
      ["Què ha d'incloure, en general, una notificació administrativa?",["Només el nom de l'òrgan","El text íntegre i la informació sobre els recursos procedents","Únicament la data de signatura","Sempre una còpia de tot l'expedient"],1,"La notificació ha d'incloure el text íntegre de la resolució i la informació legalment exigida sobre recursos."],
      ["Quin és, amb caràcter general, l'efecte del silenci en procediments iniciats a sol·licitud de l'interessat?",["Sempre desestimatori","Sempre estimatori sense excepcions","Estimatori, amb les excepcions legals","La nul·litat automàtica del procediment"],2,"La regla general és el silenci estimatori, amb excepcions legals en què és desestimatori."]
,
      ["Què regula l’article 1 de la Llei 39/2015?",["El procediment administratiu comú de les administracions públiques","L’organització dels tribunals","El règim electoral municipal","El procediment penal"],0,"L’article 1 defineix l’objecte de la Llei: regular els requisits de validesa i eficàcia dels actes administratius i el procediment administratiu comú."],
      ["Qui té capacitat d’obrar davant les administracions públiques segons l’article 3?",["Només les persones majors de 25 anys","Les persones físiques o jurídiques que la tenen d’acord amb les normes civils, i altres supòsits previstos legalment","Només les persones amb nacionalitat espanyola","Exclusivament les persones interessades ja reconegudes en una resolució"],1,"L’article 3 regula la capacitat d’obrar i inclou els supòsits que determinen les normes aplicables."],
      ["Quan s’ha de tenir la condició de persona interessada en un procediment?",["Només després de la resolució final","Quan es compleixin els requisits de l’article 4, per exemple tenir drets o interessos legítims afectats","Només quan ho autoritzi l’alcalde","En qualsevol procediment, sense relació amb el seu objecte"],1,"L’article 4 considera interessades, entre d’altres, les persones que promouen el procediment com a titulars de drets o interessos legítims i les que poden resultar afectades."],
      ["Què han de fer les persones interessades quan actuen mitjançant representant?",["La representació és sempre prohibida","Acreditar la representació per als actes que ho requereixin, sens perjudici dels mitjans admesos legalment","Presentar sempre un poder notarial, sense excepcions","Demanar autorització judicial en tots els casos"],1,"Els articles 5 i 6 regulen la representació i els registres electrònics d’apoderaments; l’acreditació es pot fer pels mitjans admesos legalment."],
      ["Quina és la regla general sobre l’obligació de relacionar-se electrònicament amb l’Administració?",["Totes les persones físiques hi estan obligades en qualsevol cas","Les persones físiques poden escollir el mitjà, llevat que estiguin obligades legalment a relacionar-s’hi electrònicament","Només es permet el paper","Només els càrrecs electes poden fer tràmits electrònics"],1,"L’article 14 permet, amb caràcter general, que les persones físiques escullin el mitjà, amb les excepcions dels col·lectius obligats."],
      ["Què és un registre electrònic d’apoderaments?",["Un registre de sancions fermes","Un sistema per inscriure apoderaments per actuar davant les administracions en els termes legals","Una base de dades policial d’identificacions","Un registre exclusiu de contractistes"],1,"L’article 6 regula els registres electrònics d’apoderaments de les administracions públiques."],
      ["Què passa si una norma no fixa termini màxim per resoldre?",["El termini general és de sis mesos","El termini màxim és de tres mesos, llevat que una norma amb rang de llei o el dret de la UE estableixi un altre termini","No hi ha obligació de resoldre","El termini és sempre de deu dies"],1,"L’article 21.3 estableix, amb excepcions, un termini màxim de tres mesos quan la norma reguladora no fixa un termini."],
      ["Quin deure té l’Administració en els procediments administratius?",["Resoldre expressament i notificar la resolució en tots els procediments, amb les excepcions legals","Resoldre només si ho demana una persona interessada","Resoldre únicament els procediments sancionadors","No notificar les resolucions desfavorables"],0,"L’article 21 estableix l’obligació de dictar resolució expressa i notificar-la en els termes que preveu la llei."],
      ["Com es computen els terminis expressats en hores?",["Per hores hàbils, amb les regles de l’article 30","Sempre com a hores naturals sense excepcions","Només durant l’horari d’atenció presencial","Per dies complets"],0,"L’article 30 regula el còmput dels terminis; els terminis assenyalats per hores es compten d’hora en hora i de minut en minut, dins dels límits legals."],
      ["Què passa si l’últim dia d’un termini és inhàbil?",["El termini venç el dia hàbil anterior","S’entén prorrogat al primer dia hàbil següent","El procediment caduca automàticament","El termini queda suspès indefinidament"],1,"D’acord amb l’article 30, si l’últim dia del termini és inhàbil, s’entén prorrogat al primer dia hàbil següent."],
      ["Quan pot l’Administració ampliar un termini?",["Sempre, encara que el termini ja hagi vençut","Excepcionalment, si les circumstàncies ho aconsellen i no es perjudiquen drets de tercers, abans que venci el termini i dins dels límits legals","Només amb consentiment judicial","Mai, en cap procediment"],1,"L’article 32 regula l’ampliació de terminis i exigeix acordar-la abans del venciment, amb els límits establerts."],
      ["Quina conseqüència té, com a regla general, un defecte formal en un acte administratiu?",["Sempre provoca nul·litat de ple dret","Només determina anul·labilitat quan l’acte manca dels requisits formals indispensables per assolir la finalitat o causa indefensió","Mai no té conseqüències","Converteix automàticament l’acte en delicte"],1,"L’article 48.2 estableix que el defecte de forma només determina anul·labilitat en els supòsits que especifica."],
      ["Quins actes són nuls de ple dret segons l’article 47?",["Tots els actes amb qualsevol error material","Els que incorren en alguna de les causes taxades legalment, com vulnerar drets susceptibles d’empara constitucional","Només els actes dictats verbalment","Tots els actes desfavorables"],1,"L’article 47 enumera les causes de nul·litat de ple dret; no qualsevol irregularitat comporta aquesta conseqüència."],
      ["Quin és el termini general per interposar recurs d’alçada contra un acte exprés?",["De deu dies","D’un mes","De tres mesos","D’un any"],1,"L’article 122 estableix, contra actes expressos, el termini d’un mes per interposar recurs d’alçada."],
      ["Contra quins actes es pot interposar recurs potestatiu de reposició?",["Contra actes que posen fi a la via administrativa, davant el mateix òrgan que els ha dictat","Contra qualsevol acte de tràmit, sempre davant el jutjat","Només contra reglaments","Exclusivament contra sentències judicials"],0,"L’article 123 regula el recurs potestatiu de reposició contra actes que posen fi a la via administrativa, davant el mateix òrgan que els ha dictat."]
,
      ["Quina és la regla general sobre el silenci administratiu en procediments iniciats a sol·licitud de la persona interessada?",["És estimatori, llevat de les excepcions legals","Sempre és desestimatori","Sempre comporta caducitat","No existeix el silenci administratiu"],0,"L’article 24 estableix la regla general del silenci estimatori en procediments iniciats a sol·licitud, amb excepcions expressament previstes."],
      ["En un procediment iniciat d’ofici que pugui reconèixer drets o situacions favorables, quin efecte pot tenir la manca de resolució dins de termini?",["Sempre estimació de la pretensió","Els interessats que hagin comparegut poden entendre desestimades les pretensions en els termes de l’article 25","Caducitat automàtica en tots els casos","Conversió en procediment sancionador"],1,"L’article 25 regula els efectes de la manca de resolució expressa en procediments iniciats d’ofici; en determinats casos, les pretensions poden entendre’s desestimades."],
      ["Quan es pot declarar la caducitat d’un procediment iniciat a sol·licitud de la persona interessada?",["Quan la paralització sigui imputable a la persona interessada i l’Administració l’adverteixi en els termes legals","Sempre que passin deu dies","Quan l’Administració no tingui personal suficient","Quan hi hagi qualsevol informe desfavorable"],0,"L’article 95 regula la caducitat per paralització imputable a la persona interessada, amb advertiment previ i els requisits que estableix."],
      ["Quina és la regla general sobre la motivació dels actes administratius?",["Tots els actes s’han de motivar amb el mateix nivell de detall","Els actes han de motivar-se en els supòsits previstos a l’article 35, amb referència succinta de fets i fonaments de dret","No cal motivar mai les sancions","Només es motiven els actes favorables"],1,"L’article 35 enumera els actes que han de ser motivats i exigeix expressar succintament els fets i fonaments de dret."],
      ["Quina informació ha d’incloure, amb caràcter general, la notificació d’una resolució?",["El text íntegre, si posa fi o no a la via administrativa, els recursos procedents, l’òrgan davant del qual s’han de presentar i el termini","Només la part dispositiva, sense recursos","Només el nom de l’òrgan","Únicament la data de signatura"],0,"L’article 40 estableix el contingut de la notificació, incloent-hi el text íntegre i la informació sobre recursos, òrgan i terminis."],
      ["Quan s’ha de practicar la notificació electrònica?",["Només quan la persona interessada obri un compte bancari","Mitjançant compareixença a la seu electrònica o a través de l’adreça electrònica habilitada única, segons el sistema aplicable","Sempre per missatge de text","Exclusivament mitjançant xarxes socials"],1,"L’article 43 regula la pràctica de les notificacions per mitjans electrònics i els sistemes previstos legalment."],
      ["Què és el tràmit d’audiència?",["Una fase que permet a les persones interessades examinar l’expedient i formular al·legacions abans de la proposta de resolució, en els termes legals","Una vista judicial penal obligatòria","Una notificació de sanció ferma","Una compareixença sempre oral davant l’alcalde"],0,"L’article 82 regula el tràmit d’audiència abans de redactar la proposta de resolució, amb les excepcions previstes."],
      ["Quin termini general tenen les persones interessades per formular al·legacions en el tràmit d’audiència?",["No inferior a deu dies ni superior a quinze, llevat que una norma estableixi un altre termini","Exactament 48 hores","Sempre un mes","Tres dies naturals en tots els casos"],0,"L’article 82 estableix un termini no inferior a deu dies ni superior a quinze per al tràmit d’audiència, llevat que una norma estableixi un altre termini."],
      ["Què és la tramitació simplificada del procediment administratiu comú?",["Una via que es pot acordar quan raons d’interès públic o manca de complexitat ho aconsellin, amb els requisits de l’article 96","Un procediment sense resolució final","Una forma de sancionar sense audiència en tots els casos","Un procediment exclusiu per als jutjats"],0,"L’article 96 regula la tramitació simplificada, que exigeix els pressupòsits legals i manté els tràmits que la norma determina."],
      ["Quin termini màxim general preveu l’article 96 per resoldre i notificar un procediment de tramitació simplificada?",["Deu dies","Trenta dies, comptats des del dia següent a la notificació de l’acord d’inici de la tramitació simplificada","Tres mesos","Sis mesos"],1,"L’article 96 preveu que els procediments de tramitació simplificada s’han de resoldre en trenta dies, amb les regles específiques de còmput i els tràmits que estableix."],
      ["Quina és la regla sobre l’execució dels actes administratius?",["Els actes subjectes a dret administratiu són executius d’acord amb la llei, llevat dels supòsits en què se’n suspèn l’execució o hi ha una excepció legal","Cap acte administratiu és executable","Només són executables els actes sancionadors","L’execució sempre requereix sentència judicial"],0,"L’article 98 estableix la regla general d’executivitat dels actes administratius, amb les excepcions previstes legalment."],
      ["Quin mitjà d’execució forçosa pot utilitzar l’Administració quan concorren els requisits legals?",["Constrenyiment sobre el patrimoni, execució subsidiària, multa coercitiva o compulsió sobre les persones, segons el cas","Només la detenció policial","Únicament la publicació al tauler d’anuncis","Sempre la confiscació de béns"],0,"L’article 100 enumera els mitjans d’execució forçosa i exigeix respectar la proporcionalitat i les garanties legals."],
      ["Quin termini general hi ha per interposar un recurs potestatiu de reposició contra un acte exprés?",["Deu dies","Un mes","Tres mesos","Un any"],1,"L’article 124 estableix el termini d’un mes per interposar recurs potestatiu de reposició contra un acte exprés."],
      ["Què passa si una persona presenta un recurs davant l’òrgan que ha dictat l’acte, però l’ha de resoldre l’òrgan superior?",["L’òrgan que el rep l’ha de trametre a l’òrgan competent en el termini legal, amb informe i expedient","El recurs és nul automàticament","La persona ha de tornar-lo a presentar necessàriament","L’acte impugnat queda anul·lat sense resolució"],0,"L’article 121.2 permet presentar el recurs d’alçada davant l’òrgan que va dictar l’acte; aquest l’ha de trametre al competent en deu dies amb informe i còpia completa i ordenada de l’expedient."],
      ["Quin és el termini general per interposar recurs extraordinari de revisió quan es fonamenta en un error de fet que resulta dels documents incorporats a l’expedient?",["Un mes","Tres mesos des del coneixement de l’error","Quatre anys des de la notificació de l’acte","Deu dies"],2,"L’article 125 fixa quatre anys des de la notificació de la resolució impugnada per a la causa d’error de fet; per a les altres causes, el termini és de tres mesos."]
    ],
    "40":[
      ["Quina matèria regula principalment la Llei 40/2015?",["El règim jurídic del sector públic","El Codi penal","El procediment laboral privat","Els arrendaments urbans"],0,"La Llei 40/2015 regula les bases del règim jurídic de les administracions públiques i altres aspectes del sector públic."],
      ["Quin principi ha de respectar l'actuació administrativa?",["Arbitrarietat","Eficàcia i coordinació","Secret absolut en tots els actes","Preferència per interessos particulars"],1,"L'eficàcia i la coordinació són principis de l'actuació i de les relacions entre administracions."],
      ["Què implica el principi d'irrenunciabilitat de la competència?",["Que cada òrgan pot renunciar-hi lliurement","Que l'ha d'exercir l'òrgan que la té atribuïda, llevat dels supòsits legals","Que la competència passa automàticament a un altre òrgan","Que no existeixen delegacions"],1,"La competència és irrenunciable i l'exerceix l'òrgan que la té atribuïda, sens perjudici de les tècniques previstes legalment."],
      ["Quina figura permet encarregar l'exercici d'una competència a un altre òrgan en els termes legals?",["Delegació de competències","Renúncia de competència","Desistiment","Caducitat automàtica"],0,"La delegació de competències és una tècnica prevista a la Llei 40/2015."],
      ["Quin d'aquests requisits es vincula al dany indemnitzable en la responsabilitat patrimonial?",["Qualsevol dany que s'hagi de suportar jurídicament","Dany efectiu, avaluable econòmicament i individualitzat","Només danys intencionats","Només danys contractuals"],1,"Entre els requisits hi ha que el dany sigui efectiu, avaluable econòmicament i individualitzat."]
,
      ["Quin és l’objecte principal de la Llei 40/2015?",["El règim jurídic del sector públic i les bases de l’organització i funcionament administratiu que regula","El procediment penal","El règim electoral general","La regulació dels contractes entre particulars"],0,"La Llei 40/2015 regula el règim jurídic del sector públic, incloent-hi les bases de l’organització administrativa, els principis de responsabilitat i altres matèries."],
      ["Quin principi regeix les relacions entre administracions públiques?",["Lleialtat institucional i cooperació, en els termes legals","Dependència jeràrquica universal entre totes les administracions","Subordinació automàtica dels ajuntaments a qualsevol altra administració","Secret absolut de les actuacions"],0,"La Llei 40/2015 recull principis com la lleialtat institucional, la cooperació, la col·laboració i la coordinació."],
      ["Què implica la competència administrativa?",["Que cada òrgan pot exercir qualsevol funció pública","Que l’exerceix l’òrgan que la té atribuïda com a pròpia, sens perjudici de les tècniques legals de transferència o delegació d’exercici","Que es pot renunciar lliurement a exercir-la","Que només existeix si hi ha autorització judicial"],1,"L’article 8 estableix la irrenunciabilitat de la competència i que l’ha d’exercir l’òrgan que la té atribuïda, amb les excepcions legals."],
      ["Quina diferència bàsica hi ha entre delegació de competències i avocació?",["La delegació permet encomanar l’exercici a un altre òrgan; l’avocació permet que un òrgan superior assumeixi un assumpte atribuït ordinàriament a un inferior, quan la llei ho permet","Són exactament el mateix","L’avocació només la pot fer una persona particular","La delegació elimina definitivament la titularitat de la competència"],0,"Els articles 9 i 10 regulen la delegació de competències i l’avocació, que són tècniques diferents i subjectes a requisits."],
      ["Es poden delegar competències en qualsevol supòsit?",["Sí, sempre i sense excepcions","No; la Llei 40/2015 exclou determinades competències de la delegació","Només les competències sancionadores","Només quan ho autoritzi un tribunal penal"],1,"L’article 9.2 enumera competències que no poden ser objecte de delegació, amb els matisos previstos legalment."],
      ["Què és l’encàrrec de gestió?",["La cessió de la titularitat d’una competència a una empresa privada","L’encàrrec d’activitats materials o tècniques de competència d’un òrgan o entitat a un altre, sense cedir-ne la titularitat","Una sanció disciplinària","Una forma de recurs administratiu"],1,"L’article 11 regula l’encàrrec de gestió d’activitats materials o tècniques, sense cessió de la titularitat de la competència."],
      ["Què és la delegació de signatura?",["Una transferència de titularitat de la competència","L’autorització perquè un titular o òrgan delegui la signatura en els termes legals, sense alterar la competència","Una delegació de potestat legislativa","Una forma de silenci administratiu"],1,"L’article 12 regula la delegació de signatura i estableix que no altera la competència de l’òrgan delegant."],
      ["Què implica la suplència d’un titular d’òrgan administratiu?",["Que la competència es transfereix definitivament","Que una altra persona exerceix temporalment les funcions en els casos previstos, sense alterar la competència","Que s’extingeix l’òrgan administratiu","Que cal dissoldre l’Administració"],1,"L’article 13 regula la suplència en supòsits com vacant, absència o malaltia, sense que impliqui alteració de la competència."],
      ["Quan s’ha d’abstenir una autoritat o empleat públic?",["Quan concorre alguna de les causes legals d’abstenció, com tenir interès personal en l’assumpte","Només quan ho demani un mitjà de comunicació","Mai, perquè l’abstenció és voluntària en tots els casos","Sempre que conegui una de les persones interessades"],0,"L’article 23 regula les causes d’abstenció, entre les quals hi ha l’interès personal, determinats vincles familiars o amistat íntima o enemistat manifesta."],
      ["Què pot fer una persona interessada si considera que una autoritat està incursa en una causa d’abstenció?",["Plantejar-ne la recusació en els termes previstos legalment","Destituir-la directament","Anul·lar per si mateixa el procediment","Imposar-li una sanció penal"],0,"L’article 24 regula la recusació, que pot promoure la persona interessada quan concorre una causa legal."],
      ["Quins requisits generals ha de reunir un dany perquè sigui indemnitzable per responsabilitat patrimonial?",["Ha de ser efectiu, avaluable econòmicament i individualitzat respecte d’una persona o grup de persones","Ha de ser hipotètic i general","Ha de derivar sempre d’una actuació dolosa","Només pot ser moral i no quantificable"],0,"L’article 32 estableix, entre altres requisits, que el dany sigui efectiu, avaluable econòmicament i individualitzat."],
      ["L’Administració respon patrimonialment de qualsevol perjudici causat a una persona?",["Sí, sense cap requisit","No; cal que es compleixin els requisits legals i que el perjudici no sigui un dany que la persona tingui el deure jurídic de suportar","Només si el perjudici és intencionat","Només quan hi ha un contracte"],1,"La responsabilitat patrimonial no és automàtica: s’han de complir els requisits de la Llei 40/2015, inclòs que el dany no sigui jurídicament exigible de suportar."],
      ["Quin principi regeix la potestat sancionadora de les administracions?",["Legalitat, tipicitat, proporcionalitat i responsabilitat, entre els principis previstos legalment","Llibertat absoluta per crear infraccions","Aplicació retroactiva de qualsevol sanció desfavorable","Imposició de sancions sense procediment"],0,"Els articles 25 a 31 recullen els principis de la potestat sancionadora, incloent-hi legalitat, tipicitat, responsabilitat, proporcionalitat i prescripció."],
      ["Es pot imposar una sanció administrativa que impliqui directament privació de llibertat?",["Sí, si ho acorda l’alcalde","No; les administracions civils no poden imposar sancions que impliquin directament o subsidiàriament privació de llibertat","Sí, en infraccions de trànsit","Només en procediments d’urgència"],1,"L’article 29.1 estableix que les sancions administratives no poden implicar, directament o subsidiàriament, privació de llibertat."],
      ["Quan prescriu una infracció administrativa?",["Sempre al cap d’un mes","D’acord amb els terminis que estableixi la normativa aplicable; si no n’hi ha, s’apliquen els terminis supletoris de l’article 30","Mai no prescriu","Sempre als deu anys"],1,"L’article 30 regula la prescripció de les infraccions i preveu terminis supletoris quan no n’hi ha d’altres establerts per llei."]
    ],
    "4":[
      ["Quin és l'objecte de la Llei orgànica 4/2015?",["La protecció de la seguretat ciutadana","Les eleccions municipals","La contractació pública","La protecció civil exclusivament"],0,"La Llei orgànica 4/2015 té per objecte la protecció de la seguretat ciutadana."],
      ["L'actuació policial en matèria de seguretat ciutadana ha de respectar:",["Només les instruccions internes","Els principis de legalitat, proporcionalitat i no-discriminació, entre d'altres","Exclusivament la conveniència","La voluntat del denunciant"],1,"Les actuacions s'han d'ajustar als principis i garanties previstos per la llei i la resta de l'ordenament."],
      ["Quin criteri ha de regir les mesures d'intervenció policial?",["La màxima intensitat en tots els casos","La proporcionalitat segons les circumstàncies i el marc legal","La decisió del particular","La mesura més restrictiva automàticament"],1,"La intervenció ha de respectar la proporcionalitat i les garanties legals aplicables."],
      ["La identificació de persones en l'àmbit de la seguretat ciutadana:",["Es pot fer sense pressupòsit legal","S'ajusta als supòsits, finalitats i garanties establerts legalment","Permet retenir indefinidament","Sempre equival a una detenció penal"],1,"La identificació s'ha de practicar d'acord amb els supòsits i garanties que preveu la normativa."],
      ["Què s'ha de tenir present en imposar una sanció administrativa?",["La tipificació legal i les garanties del procediment","Només la percepció de l'agent","Que no cal motivar la decisió","Que les sancions es creen per instrucció interna"],0,"La potestat sancionadora està sotmesa als principis de legalitat, tipicitat, proporcionalitat i procediment."]
,
      ["Quina finalitat té la Llei orgànica 4/2015?",["Protegir la seguretat ciutadana i regular les actuacions administratives previstes en aquesta matèria","Regular exclusivament la investigació penal","Establir les competències dels jutjats","Regular només el trànsit urbà"],0,"L’article 1 estableix l’objecte de la Llei orgànica 4/2015, de protecció de la seguretat ciutadana."],
      ["Quins principis han de respectar les autoritats i els agents en les seves actuacions?",["Legalitat, igualtat de tracte i no-discriminació, oportunitat, proporcionalitat i responsabilitat, entre d’altres","Discrecionalitat sense control","Prioritat automàtica de la comoditat del servei","Secret absolut davant de qualsevol requeriment legal"],0,"L’article 4 recull els principis rectors de l’actuació dels poders públics en matèria de seguretat ciutadana."],
      ["Quan es pot requerir la identificació d’una persona a la via pública segons l’article 16?",["Quan hi ha indicis de participació en una infracció o és raonablement necessari per prevenir un delicte, en els supòsits legals","Sempre que un agent vulgui identificar qualsevol vianant sense cap finalitat","Només després d’una sentència judicial","Només si la persona ho demana"],0,"L’article 16 estableix els supòsits i les finalitats que habiliten els requeriments d’identificació."],
      ["Si no és possible identificar una persona pels mitjans disponibles i concorren els requisits legals, què poden fer els agents?",["Requerir que acompanyi els agents a les dependències policials més pròximes amb mitjans adequats, exclusivament per identificar-la i dins del límit legal","Detenir-la automàticament per qualsevol infracció","Retenir-la indefinidament al carrer","Traslladar-la sempre a un centre penitenciari"],0,"L’article 16 regula el trasllat a dependències policials als efectes d’identificació i n’estableix garanties i límits temporals."],
      ["Quina garantia s’aplica a les diligències d’identificació a dependències policials?",["Cal portar un llibre-registre i deixar constància de les diligències en els termes legals","No cal documentar-les","Només se’n deixa constància si la persona ho sol·licita per escrit","S’han de publicar les dades identificatives de la persona"],0,"L’article 16 preveu garanties documentals i de control per a les diligències d’identificació."],
      ["Què regula l’article 17 de la Llei orgànica 4/2015?",["Els controls a les vies públiques en els supòsits legalment previstos","La composició del Congrés dels Diputats","La tramitació de recursos contenciosos administratius","La regulació de permisos de conduir"],0,"L’article 17 regula els controls en les vies públiques per prevenir la comissió de delictes d’especial gravetat o generar un risc greu per a les persones i els béns, dins dels requisits legals."],
      ["Quin criteri s’ha de respectar en els escorcolls corporals externs superficials previstos a l’article 20?",["Que siguin necessaris, adequats i proporcionats, amb les garanties que estableix la llei","Que es facin sempre a totes les persones identificades","Que no calgui cap justificació","Que tinguin finalitat sancionadora"],0,"L’article 20 regula els escorcolls corporals externs superficials i exigeix justificació i respecte a les garanties legals."],
      ["Quan es poden ocupar temporalment objectes o instruments susceptibles de ser utilitzats per a accions il·legals?",["En els supòsits legalment previstos i quan sigui necessari per prevenir la comissió d’un delicte o garantir la seguretat ciutadana","Sempre que l’objecte sigui de valor","Només amb autorització del propietari","Mai, en cap circumstància"],0,"La Llei orgànica 4/2015 permet determinades mesures d’intervenció i ocupació d’objectes quan concorren els pressupòsits legals."],
      ["Quina és la regla general sobre les reunions i manifestacions en llocs de trànsit públic?",["S’han de comunicar prèviament a l’autoritat en els termes de la Llei orgànica 9/1983; la comunicació no equival a una autorització general","Necessiten sempre autorització discrecional de l’alcalde","Estan prohibides en tots els espais públics","Només les poden convocar partits polítics"],0,"El règim general de comunicació prèvia de reunions i manifestacions en llocs de trànsit públic es troba a la Llei orgànica 9/1983; no s’ha de confondre amb una autorització general."],
      ["Quina conducta pot constituir una infracció greu segons la Llei orgànica 4/2015?",["La desobediència o resistència a l’autoritat o als seus agents, quan no sigui constitutiva de delicte","Qualsevol crítica verbal a un agent","Qualsevol negativa a respondre preguntes no obligatòries","Qualsevol reunió pacífica comunicada"],0,"L’article 36 tipifica diverses infraccions greus, inclosa la desobediència o resistència a l’autoritat o als seus agents quan no constitueixi delicte."],
      ["Quina conducta pot constituir una infracció lleu segons l’article 37?",["La manca de respecte i consideració a un membre de les Forces i Cossos de Seguretat en l’exercici de les seves funcions, quan no sigui delicte","Qualsevol delicte contra l’autoritat","La resistència greu constitutiva de delicte","Qualsevol manifestació pacífica"],0,"L’article 37 recull infraccions lleus, inclosa la manca de respecte i consideració en els termes exactes previstos legalment."],
      ["Qui pot ser responsable d’una infracció administrativa en matèria de seguretat ciutadana?",["La persona física o jurídica a qui la llei atribueixi responsabilitat per la conducta tipificada","Sempre el titular de l’alcaldia","Només el propietari de l’immoble més proper","Qualsevol persona present al lloc"],0,"La responsabilitat s’ha de determinar d’acord amb els principis i les regles de la Llei orgànica 4/2015; no es pot atribuir automàticament a qualsevol persona present."],
      ["Quin principi limita la quantia de les sancions?",["La proporcionalitat, atenent els criteris legalment previstos","La decisió lliure de l’agent actuant","El nombre de testimonis, com a únic criteri","La capacitat de pagament, com a únic criteri"],0,"La Llei orgànica 4/2015 estableix criteris de graduació de les sancions i exigeix respectar el principi de proporcionalitat."],
      ["Quin termini general de prescripció tenen les infraccions lleus segons l’article 38 de la Llei orgànica 4/2015?",["Sis mesos","Un mes","Tres mesos","Un any"],0,"L’article 38 estableix que les infraccions lleus prescriuen al cap de sis mesos, les greus al cap d’un any i les molt greus al cap de dos anys."],
      ["Una persona és identificada en una actuació policial. Es poden difondre lliurement les seves dades personals a les xarxes socials del cos?",["No; cal respectar la normativa de protecció de dades, la finalitat de l’actuació i els drets de la persona","Sí, si la identificació s’ha fet en un lloc públic","Sí, sempre que no hi hagi una denúncia","Només cal ocultar el número del document"],0,"Les dades personals obtingudes en actuacions policials no es poden difondre lliurement; s’han de respectar la normativa aplicable i els límits de finalitat i proporcionalitat."]
    ],
    "16":[
      ["Quina norma regula específicament les policies locals a Catalunya?",["Llei 16/1991, de 10 de juliol","Llei orgànica 4/2015","Llei 39/2015","Reial decret legislatiu 6/2015"],0,"La Llei 16/1991, de 10 de juliol, regula les policies locals de Catalunya. Consulta el text vigent al Portal Jurídic de Catalunya."],
      ["Quin és un àmbit d'actuació de les policies locals previst a la Llei 16/1991?",["Exercir funcions de policia judicial en els termes legals","Aprovar lleis autonòmiques","Dirigir els jutjats de pau","Imposar penes privatives de llibertat"],0,"La normativa atribueix funcions de policia judicial en els termes establerts per l'ordenament jurídic i la coordinació policial."],
      ["En relació amb la policia local, qui exerceix el comandament superior del cos en l'àmbit municipal d'acord amb el marc legal?",["L'alcalde o alcaldessa, sens perjudici de les delegacions legalment possibles","El jutjat de guàrdia","El delegat del Govern sempre","El cap de la policia autonòmica"],0,"El comandament de la policia local s'insereix en l'organització municipal i s'ha d'interpretar d'acord amb la Llei 16/1991 i la normativa de règim local."],
      ["Les policies locals de Catalunya formen part de:",["Els cossos de seguretat d'àmbit local","L'Administració de justícia","Les Forces Armades","Els serveis penitenciaris"],0,"Les policies locals són cossos de seguretat d'àmbit local, amb les funcions i principis que estableix la legislació aplicable."],
      ["L'actuació de les policies locals s'ha d'ajustar:",["Als principis bàsics d'actuació de la normativa de forces i cossos de seguretat","Només a les ordres verbals de qualsevol autoritat","A criteris diferents per a cada agent","Exclusivament a les ordenances municipals"],0,"Els principis bàsics d'actuació inclouen el respecte a la Constitució i a la llei, la neutralitat, la integritat i la proporcionalitat. Cal contrastar cada supòsit amb la normativa vigent."],
      ["Quina actuació de trànsit correspon habitualment a la policia local dins del nucli urbà?",["Ordenar, senyalitzar i dirigir el trànsit d'acord amb les normes de circulació","Expedir permisos de conduir","Aprovar el reglament general de circulació","Gestionar exclusivament les autopistes estatals"],0,"La Llei 16/1991 inclou entre les funcions de la policia local ordenar, senyalitzar i dirigir el trànsit en el nucli urbà, d'acord amb les normes de circulació."],
      ["En quin àmbit territorial actua ordinàriament una policia local?",["Al terme municipal corresponent","A tot Catalunya sense cap condició","Només a les dependències municipals","A tot l'Estat"],0,"L'àmbit ordinari d'actuació és el territori del municipi corresponent. Les actuacions fora d'aquest àmbit estan subjectes a supòsits i autoritzacions previstos legalment."],
      ["Què han de fer les policies locals respecte dels accidents de circulació al nucli urbà?",["Poden instruir atestats i comunicar les actuacions als cossos competents","Només poden fer fotografies","No poden intervenir-hi","Han de remetre sempre el cas a una empresa privada"],0,"La normativa atribueix la instrucció d'atestats per accidents de circulació esdevinguts dins el nucli urbà, amb comunicació de les actuacions als cossos competents."],
      ["Quina funció correspon a la policia administrativa local?",["Vetllar pel compliment de les ordenances i disposicions municipals aplicables","Modificar ordenances sense acord municipal","Resoldre recursos judicials","Aprovar sancions penals"],0,"La policia local exerceix funcions de policia administrativa per assegurar el compliment de les ordenances, bans i altres disposicions municipals, d'acord amb la normativa."],
      ["Quina actuació s'inclou en la prevenció del delicte?",["Fer diligències de prevenció i comunicar-les als cossos competents quan correspongui","Investigar qualsevol delicte sense límits territorials ni legals","Substituir el ministeri fiscal","Imposar penes privatives de llibertat"],0,"La Llei 16/1991 inclou diligències de prevenció i actuacions destinades a evitar actes delictuosos, amb la comunicació corresponent."],
      ["Quan poden actuar fora del seu terme municipal?",["En situacions d'emergència i amb l'autorització prèvia de les autoritats competents, segons la informació oficial","Sempre que ho decideixi individualment un agent","Mai, en cap circumstància","Quan ho demani qualsevol particular, sense més requisits"],0,"El Departament d'Interior indica que l'actuació fora de l'àmbit territorial municipal és possible en situacions d'emergència i amb autorització prèvia de les autoritats competents."],
      ["Quina actuació s'associa a la policia local en protecció civil?",["Auxiliar en accidents, catàstrofes i calamitats públiques en els termes legals","Declarar unilateralment l'estat d'alarma","Dirigir els bombers en tots els supòsits","Substituir els serveis sanitaris"],0,"Entre les funcions policials locals hi ha prestar auxili en accidents, catàstrofes i calamitats públiques i participar en plans de protecció civil d'acord amb la llei."],
      ["Quin és un àmbit d'actuació reconegut de les policies locals a Catalunya?",["Policia administrativa","Control de fronteres internacionals","Defensa militar","Expedició de passaports"],0,"El Departament d'Interior identifica, entre altres, els àmbits de trànsit, seguretat ciutadana, policia administrativa, assistencial i judicial."],
      ["Quina tasca de cooperació pot correspondre a les policies locals?",["Col·laborar amb altres cossos policials en els supòsits previstos legalment","Assumir automàticament totes les competències dels Mossos d'Esquadra","Donar ordres a qualsevol cos policial fora del municipi","Substituir els jutjats en investigacions"],0,"La normativa preveu funcions de col·laboració i cooperació amb altres forces i cossos de seguretat en els supòsits legalment establerts."],
      ["Quina naturalesa tenen les policies locals segons l'article 2.1?",["Instituts armats de naturalesa civil, amb estructura i organització jerarquitzades","Cossos militars dependents de la Generalitat","Serveis administratius sense caràcter policial","Unitats judicials dependents dels tribunals"],0,"Article 2.1 de la Llei 16/1991: les policies locals són instituts armats de naturalesa civil amb estructura i organització jerarquitzades."],
      ["Com es pot denominar específicament un cos de policia local per raons de tradició històrica?",["Policia municipal o guàrdia urbana, si ho acorda la corporació local","Guàrdia civil municipal en tots els municipis","Policia judicial municipal exclusivament","Cos autonòmic de seguretat"],0,"Article 2.3: per raons de tradició històrica, la corporació local pot acordar la denominació de policia municipal o guàrdia urbana."],
      ["Quina condició es preveu per crear policia local en un municipi de menys de 10.000 habitants segons l'article 3.2?",["Acord per majoria absoluta del nombre legal de membres de la corporació i autorització del conseller competent, amb informe previ de la Comissió","Acord simple de la junta de govern, sense autorització","Autorització exclusiva del Ministeri de l'Interior","Consulta popular vinculant obligatòria"],0,"Article 3.2 de la Llei 16/1991. Cal tenir present la redacció vigent i la denominació actual dels òrgans competents."],
      ["Qui exerceix el comandament immediat de la policia local?",["El cap del cos","El ple municipal","El jutge degà","La Comissió de Coordinació"],0,"Article 4.3: el comandament immediat correspon al cap del cos."],
      ["Pot l'alcalde delegar les atribucions de comandament de la policia local?",["Sí, d'acord amb la normativa vigent","No, en cap cas","Només en el ple municipal","Només en un jutge"],0,"Article 4.2: l'alcalde exerceix el comandament i pot delegar les atribucions corresponents d'acord amb la normativa vigent."],
      ["Què exigeix l'article 5 per actuar fora del terme municipal?",["Una situació d'emergència i autorització prèvia de les autoritats competents","Una petició verbal de qualsevol ciutadà","Que l'agent estigui fora de servei","Cap condició si hi ha manca de personal"],0,"Article 5.2: l'actuació fora de l'àmbit territorial municipal només és possible en situacions d'emergència i amb autorització prèvia de les autoritats competents."],
      ["Què han de fer els agents abans de prendre possessió del càrrec?",["Jurar o prometre acatar la Constitució i respectar i observar l'Estatut d'autonomia","Jurar fidelitat a un partit polític","Aprovar una ordenança municipal","Sol·licitar autorització judicial individual"],0,"Article 6 de la Llei 16/1991: jurament o promesa d'acatar la Constitució i respectar i observar l'Estatut d'autonomia."],
      ["Quan tenen els vigilants municipals la condició d'agents de l'autoritat segons l'article 7.2?",["Quan actuen identificats i en les funcions pròpies, i el municipi no disposa de policia local","Sempre, fins i tot quan fan funcions privades","Només quan porten arma de foc","Mai, en cap supòsit"],0,"Article 7.2: la condició està subjecta a requisits, entre els quals actuar degudament identificats en les funcions pròpies i que el municipi no disposi de policia local."],
      ["Poden els vigilants municipals regulats a l'article 1.2 portar armes de foc?",["No","Sí, si ho autoritza qualsevol regidor","Sí, sempre que estiguin uniformats","Només durant els torns nocturns"],0,"Article 8.3: els vigilants a què es refereix l'article 1.2 no poden portar armes de foc."],
      ["Qui determina motivadament les circumstàncies i els serveis en què els policies locals no portaran armes de foc?",["L'alcalde","El cap de cada torn sense cap límit","El jutjat de guàrdia","La persona denunciant"],0,"Article 8.2: correspon a l'alcalde determinar-ho de forma motivada."],
      ["Per a què es pot utilitzar l'uniforme reglamentari?",["Només per al compliment del servei","Per a qualsevol activitat privada","Només per a actes institucionals","Per prestar serveis de seguretat privada"],0,"Article 9.1: l'uniforme reglamentari només pot utilitzar-se per al compliment del servei."],
      ["Què han de portar els policies locals quan estan autoritzats a prestar un servei sense uniforme?",["La documentació acreditativa de la seva condició","Necessàriament una arma llarga visible","Una autorització judicial en tots els casos","Cap identificació professional"],0,"Article 9.2: qui actua sense uniforme reglamentari ha de portar la documentació acreditativa de la seva condició."],
      ["Pot una ordre jeràrquica justificar l'execució d'un acte manifestament delictiu?",["No; l'obediència deguda no empara actes manifestament delictius o contraris a la Constitució, l'Estatut o les lleis","Sí, sempre que l'ordre sigui escrita","Sí, si ho ordena un superior jeràrquic","Només si l'acte passa durant una emergència"],0,"Article 10.1, principi d'adequació a l'ordenament jurídic: l'obediència deguda no empara actes manifestament delictius o contraris a les normes indicades."],
      ["Quin tracte han de dispensar els policies locals a la ciutadania?",["Un tracte correcte i acurat, amb auxili i protecció quan les circumstàncies ho aconsellin o siguin requerits","Un tracte diferent segons l'opinió política","Només informació si ho ordena un jutge","Cap informació sobre la finalitat de les intervencions"],0,"Article 10.1: s'exigeix un tracte correcte i esmerat i, tant com sigui possible, informació sobre les causes i la finalitat de les intervencions."],
      ["Quan es poden utilitzar les armes de foc segons els principis de l'article 10?",["En situacions de risc racionalment greu per a la vida o integritat física, o de greu risc per a la seguretat ciutadana, amb els principis aplicables","Sempre que una persona no obeeixi immediatament","Per evitar qualsevol infracció administrativa","Només quan ho demani un particular"],0,"Article 10.1: l'ús d'armes està limitat als supòsits de risc greu que estableix la llei i queda subjecte als principis de congruència, oportunitat i proporcionalitat."],
      ["Quin deure professional estableix la Llei 16/1991 sobre la informació coneguda durant el servei?",["Guardar secret professional, amb les excepcions legals","Publicar-la sempre en xarxes socials","Comunicar-la a qualsevol particular que la demani","Destruir-la en acabar el torn"],0,"Article 10.1: els policies locals han de guardar rigorós secret sobre la informació coneguda per raó o ocasió del servei, llevat dels supòsits legals."],
      ["Segons l’article 10, quan es pot justificar l’ús de les armes de foc?",["Quan existeix un risc racionalment greu per a la vida o integritat pròpia o de terceres persones, o un greu risc per a la seguretat ciutadana","Sempre que una persona no obeeixi una ordre","Per evitar qualsevol fugida, sense valorar el risc","Només quan ho autoritzi prèviament un jutge"],0,"Article 10.1, segon: l’ús d’armes queda limitat a situacions de risc racionalment greu i s’ha de regir pels principis de congruència, oportunitat i proporcionalitat. Font: BOE, Llei 16/1991."],
      ["Quin principi limita l’obediència jeràrquica dels agents?",["No s’han d’obeir ordres que constitueixin manifestament delicte o siguin contràries a la Constitució, l’Estatut o les lleis","Cal obeir sempre qualsevol ordre, sigui quin sigui el contingut","Només es poden desobeir ordres escrites","L’agent pot decidir lliurement si compleix les ordres legals"],0,"Article 10.1, primer, lletra d): la subordinació no empara ordres manifestament delictives o contràries a l’ordenament indicat."],
      ["En efectuar una detenció, quin deure específic recull l’article 10?",["Identificar-se degudament com a agent","Esperar a arribar a comissaria per identificar-se","Informar únicament els familiars","No comunicar mai la causa de la intervenció"],0,"Article 10.1, tercer, lletra a): l’agent s’ha d’identificar degudament en el moment d’efectuar la detenció."],
      ["Quin deure tenen els agents respecte de les persones detingudes o sota custòdia?",["Vetllar per la seva vida i integritat física i respectar els seus drets, honor i dignitat","Restringir-ne els drets sense cap límit","Permetre que terceres persones les interroguin lliurement","Retardar sempre els tràmits fins al canvi de torn"],0,"Article 10.1, tercer, lletra b), de la Llei 16/1991."],
      ["Què estableix la Llei 16/1991 sobre la dedicació professional?",["Cal intervenir en defensa de la llei i la seguretat ciutadana en qualsevol moment i lloc, tant si s’està de servei com si no","Només s’hi ha d’intervenir durant el torn assignat","Fora de servei només es pot actuar amb autorització de l’alcaldia","La intervenció fora de servei està sempre prohibida"],0,"Article 10.1, quart: la llei estableix el deure d’intervenir en defensa de la llei i la seguretat ciutadana, amb els límits que resultin de l’ordenament jurídic."],
      ["Quina responsabilitat preveu l’article 10.2 per als policies locals?",["Responsabilitat personal i directa pels actes o omissions que vulnerin normes i principis aplicables, sens perjudici de la responsabilitat patrimonial de l’Administració","Només responsabilitat política de l’alcaldia","Cap responsabilitat individual si hi ha una ordre superior","Exclusivament responsabilitat civil davant de particulars"],0,"Article 10.2 de la Llei 16/1991: responsabilitat personal i directa de l’agent, sense perjudici de la que pugui correspondre a l’Administració."],
      ["Un accident de circulació té lloc dins del nucli urbà. Quina funció atribueix l’article 11 a la policia local?",["Instruir l’atestat i comunicar les actuacions als cossos de seguretat competents","Imposar directament una pena penal","Traslladar sempre la investigació a una empresa privada","Actuar només si hi ha lesions greus"],0,"Article 11.c): la policia local instrueix atestats per accidents de circulació dins del nucli urbà i comunica les actuacions als cossos competents."],
      ["La policia local rep un requeriment per cooperar en un conflicte privat. Quina resposta encaixa amb l’article 11?",["Pot cooperar en la resolució del conflicte quan sigui requerida per fer-ho","Ha de resoldre’l com si fos un tribunal","Només hi pot intervenir si hi ha una ordre judicial","No pot intervenir mai en conflictes privats"],0,"Article 11.h): cooperar en la resolució de conflictes privats quan sigui requerida per fer-ho."],
      ["Quina funció de policia local està expressament prevista en matèria ambiental?",["Vetllar pel compliment de la normativa vigent sobre medi ambient i protecció de l’entorn","Aprovar autoritzacions ambientals autonòmiques en tots els casos","Substituir la inspecció de tots els organismes ambientals","Dictar normes ambientals amb rang de llei"],0,"Article 11.k) de la Llei 16/1991."],
      ["Quan han de col·laborar les policies locals amb altres forces de seguretat en manifestacions i grans concentracions?",["Quan siguin requerides per fer-ho, en els termes de l’article 11","Sempre assumint-ne el comandament","Només si ho demana un particular","Mai, perquè és una competència exclosa"],0,"Article 11.g): col·laboració amb les forces i cossos de seguretat de l’Estat i la policia autonòmica quan siguin requerides."],
      ["En funcions de policia judicial, quan poden practicar-se les primeres diligències de prevenció i custòdia?",["Per iniciativa pròpia o a requeriment de l’autoritat judicial, del Ministeri Fiscal o dels superiors jeràrquics, en els termes legals","Només després d’una sentència ferma","Exclusivament per ordre escrita de l’alcalde","Només quan ho demani la persona detinguda"],0,"Article 12.1.b): regula les primeres diligències de prevenció i custòdia de detinguts i objectes relacionats amb el delicte."],
      ["A qui s’han de comunicar les actuacions de policia judicial en els terminis legals?",["A l’autoritat judicial o al Ministeri Fiscal, d’acord amb la normativa vigent","Només a l’alcalde","Només als mitjans de comunicació","A qualsevol persona que ho sol·liciti"],0,"Article 12.1.b): les actuacions s’han de comunicar a l’autoritat judicial o al Ministeri Fiscal en els terminis legalment establerts."],
      ["Què significa coordinació de les policies locals segons l’article 14?",["Establir mitjans i sistemes de relació per possibilitar una acció conjunta i integrar les actuacions en el sistema de seguretat ciutadana","Unificar tots els ajuntaments en una única administració","Substituir les competències municipals per les estatals","Fer que tots els cossos tinguin necessàriament la mateixa plantilla"],0,"Article 14 de la Llei 16/1991: la coordinació facilita l’acció conjunta i la integració de les actuacions en el sistema de seguretat ciutadana."],
      ["Quina d’aquestes matèries pot incloure la coordinació prevista a l’article 15?",["Homogeneïtzació de mitjans tècnics i elements comuns, i establiment d’un sistema d’informació recíproca","Aprovació dels pressupostos de cada ajuntament","Nomenament directe de tots els alcaldes","Direcció ordinària de cada torn policial municipal"],0,"Article 15.1.a) i b): homogeneïtzació de mitjans tècnics i instruments d’informació recíproca."],
      ["Quin límit estableix l’article 15.2 a les funcions de coordinació?",["S’han de respectar l’autonomia local i les competències municipals en matèria de policia local","La coordinació elimina tota autonomia municipal","Les funcions de coordinació només es poden exercir amb autorització judicial","La coordinació pot modificar qualsevol ordenança municipal directament"],0,"Article 15.2 de la Llei 16/1991: la coordinació ha de respectar l’autonomia local i les competències municipals."],
      ["Quina documentació han de trametre i fer pública anualment les corporacions locals amb policia local o vigilants, segons l’article 20?",["La memòria dels serveis de l’any anterior i la dotació de recursos humans i materials","Només la relació de sancions de trànsit","Exclusivament el pressupost municipal","La llista de totes les persones identificades al municipi"],0,"Article 20.1: en el primer trimestre de cada any s’ha d’enviar al departament competent i fer pública la memòria dels serveis prestats l’any anterior i la dotació de recursos humans i materials."] ,
    ],
    trafic:[
      ["Quina és la norma estatal bàsica en matèria de trànsit i seguretat viària?",["Reial decret legislatiu 6/2015","Llei 39/2015 exclusivament","Llei orgànica 4/2015 exclusivament","Codi civil"],0,"El Reial decret legislatiu 6/2015 aprova el text refós de la Llei sobre trànsit, circulació de vehicles de motor i seguretat viària."],
      ["Quina obligació general tenen els usuaris de la via?",["No tenir en compte altres usuaris","No entorpir indegudament la circulació ni causar perill o dany","Respectar només senyals verticals","Aturar-se davant de qualsevol vehicle estacionat"],1,"Els usuaris de la via han d'evitar causar perill, perjudicis o molèsties innecessàries."],
      ["Què ha de fer un conductor davant la llum vermella fixa d'un semàfor?",["Accelerar si no veu vehicles","Aturar-se al lloc reglamentari","Continuar si gira a la dreta en tots els casos","Cedir el pas només als vianants"],1,"La llum vermella fixa prohibeix el pas i obliga a aturar-se en el lloc reglamentari."],
      ["Què obliga a fer un senyal de STOP?",["Reduir la velocitat i continuar si no hi ha ningú","Aturar-se i cedir el pas segons les normes aplicables","Aturar-se només si hi ha un agent","Cedir el pas només als vehicles pesants"],1,"El senyal STOP obliga a aturar-se i cedir el pas conforme a les normes de prioritat."],
      ["L'ús del cinturó de seguretat:",["Només és obligatori en autopistes","És obligatori segons la normativa vigent, amb les excepcions previstes","Només és obligatori per al conductor","Depèn de l'asseguradora"],1,"La normativa estableix l'obligació d'utilitzar els cinturons i preveu excepcions concretes.",
      ["Quina norma aprova el Reglament general de circulació?",["Reial decret 1428/2003","Reial decret legislatiu 6/2015","Llei orgànica 4/2015","Reial decret 818/2009"],0,"El Reglament general de circulació s’aprova pel Reial decret 1428/2003; el Reial decret legislatiu 6/2015 aprova el text refós de la Llei de trànsit."],
      ["Quina norma regula amb caràcter general els permisos de conduir?",["Reial decret 818/2009, que aprova el Reglament general de conductors","Reial decret 1428/2003","Llei 39/2015","Llei 16/1991"],0,"El Reglament general de conductors va ser aprovat pel Reial decret 818/2009, sens perjudici de les modificacions posteriors."],
      ["Quina obligació té el conductor davant d’un semàfor amb llum groga fixa?",["Accelerar sempre per passar abans que canviï","Aturar-se com davant la llum vermella, llevat que no es pugui fer amb seguretat suficient","Continuar sense reduir la velocitat","Aturar-se només si hi ha vianants"],1,"La llum groga fixa obliga a aturar-se, llevat que quan s’encén el vehicle estigui tan a prop que no pugui fer-ho en condicions de seguretat suficients."],
      ["Què indica una llum groga intermitent en un semàfor?",["Sempre prohibeix el pas absolutament","Permet passar amb precaució, respectant la prioritat i la resta de senyals","Dona prioritat absoluta al vehicle","Només s’aplica als vianants"],1,"La llum groga intermitent obliga a extremar la precaució i, si escau, cedir el pas; no eximeix de complir la resta de senyals."],
      ["En una intersecció sense senyalització específica, quina regla general de prioritat s’aplica?",["Prioritat del vehicle més gran","Prioritat del vehicle que s’aproximi per la dreta, amb les excepcions reglamentàries","Prioritat del vehicle que circuli més ràpid","Prioritat del vehicle que toqui el clàxon"],1,"El Reglament general de circulació estableix com a regla general la prioritat del vehicle que s’aproxima per la dreta, amb excepcions previstes reglamentàriament."],
      ["Quina velocitat màxima genèrica s’aplica als turismes en vies urbanes amb un únic carril per sentit de circulació?",["20 km/h","30 km/h","50 km/h","60 km/h"],1,"La regla general urbana fixa 30 km/h en vies d’un únic carril per sentit, 20 km/h en vies amb plataforma única i 50 km/h en vies de dos o més carrils per sentit, sens perjudici de la senyalització."],
      ["En una via urbana amb plataforma única de calçada i vorera, quina és la velocitat màxima genèrica?",["20 km/h","30 km/h","40 km/h","50 km/h"],0,"La velocitat màxima genèrica és de 20 km/h en vies urbanes amb plataforma única de calçada i vorera, llevat de senyalització diferent."],
      ["Què ha de fer un conductor si un agent regula el trànsit amb senyals diferents dels semàfors?",["Obeir sempre el semàfor encara que contradigui l’agent","Atendre les indicacions de l’agent, que prevalen sobre la resta de senyals en cas de contradicció","Seguir el vehicle precedent","Escollir la indicació més favorable"],1,"Les indicacions dels agents de l’autoritat responsables del trànsit prevalen sobre els altres senyals i normes de circulació en els termes reglamentaris."],
      ["Quina conducta és obligatòria en apropar-se a un pas de vianants no regulat per semàfor?",["Mantenir la velocitat en tots els casos","Reduir la velocitat i aturar-se si cal per permetre el pas als vianants que hi tenen prioritat","Tocar el clàxon i continuar","Aturar-se només si hi ha un agent"],1,"Els conductors han de cedir el pas als vianants que circulin pels passos degudament senyalitzats i adoptar les precaucions necessàries."],
      ["Quina és la taxa màxima general d’alcohol en aire expirat per a conductors no novells ni professionals, segons el règim general vigent?",["0,15 mg/l","0,25 mg/l","0,50 mg/l","0,60 mg/l"],1,"El límit general és de 0,25 mg/l d’aire expirat (0,5 g/l en sang), amb límits inferiors per a determinats conductors i altres règims específics."],
      ["Quin límit d’alcohol en aire expirat s’aplica, amb caràcter general, als conductors novells i professionals?",["0,10 mg/l","0,15 mg/l","0,25 mg/l","0,40 mg/l"],1,"El límit general per a conductors novells i professionals és de 0,15 mg/l en aire expirat (0,3 g/l en sang), sens perjudici de canvis normatius aplicables."],
      ["Quan s’ha d’utilitzar el cinturó de seguretat?",["Només en vies interurbanes","Durant la circulació, amb les excepcions reglamentàries","Només el conductor i l’acompanyant davanter","Només quan ho indiqui un senyal"],1,"La normativa exigeix l’ús dels cinturons de seguretat en els supòsits previstos, amb excepcions concretes regulades reglamentàriament."],
      ["Què ha de fer el conductor davant d’un vehicle prioritari que circula en servei urgent i assenyala la seva presència reglamentàriament?",["Facilitar-li el pas adoptant les mesures adequades i sense crear perill","Mantenir la trajectòria encara que li impedeixi el pas","Accelerar per circular davant seu","Aturar-se sempre al mig de la calçada"],0,"Els altres usuaris han de facilitar el pas dels vehicles prioritaris en servei urgent, adoptant les mesures necessàries sense posar en perill la circulació."],
      ["En cas d’accident amb persones ferides, quin deure general té un conductor implicat?",["Abandonar el lloc si el vehicle pot circular","Aturar-se, protegir i auxiliar les víctimes i col·laborar per evitar nous perills, segons les circumstàncies","Moure sempre les persones ferides immediatament","Esperar dins del vehicle sense avisar ningú"],1,"La normativa de trànsit imposa deures d’auxili, protecció i col·laboració després d’un accident, en funció de les circumstàncies i sense generar riscos addicionals."],
      ["Quina documentació del vehicle ha de poder acreditar-se segons la normativa aplicable?",["Només el rebut de combustible","La documentació obligatòria del vehicle i la seva situació administrativa, pels mitjans admesos legalment","Només el contracte de compravenda","Exclusivament el manual d’usuari"],1,"El vehicle ha de disposar de la documentació obligatòria exigida per la normativa, sens perjudici dels mitjans electrònics o registres que permetin acreditar-ne la situació."]
]
    ]
  };
  const HISTORY_KEY = "oposiprep-history-v1";
  function loadHistory(){
    try {
      const saved = JSON.parse(localStorage.getItem(HISTORY_KEY) || "[]");
      return Array.isArray(saved) ? saved.filter(x => x && typeof x.correct === "number" && typeof x.total === "number" && typeof x.percent === "number").slice(0,50) : [];
    } catch (_) { return []; }
  }
  const state = {opposition:"policia",law:"constitucio",count:15,questions:[],index:0,answers:{},checked:{},history:loadHistory()};
  const dialog = $("#messageDialog");
  function message(title,body){$("#dialogTitle").textContent=title;$("#dialogMessage").textContent=body;if(dialog.showModal)dialog.showModal();else alert(title+"\n"+body);}
  function refreshStats(){
    const tests=state.history.length;
    const total=state.history.reduce((n,x)=>n+x.total,0);
    const hits=state.history.reduce((n,x)=>n+x.correct,0);
    $("#statTests").textContent=tests;
    $("#statAccuracy").textContent=total ? Math.round(hits/total*100)+"%" : "—";
    $("#statBest").textContent=tests ? Math.max(...state.history.map(x=>x.percent))+"%" : "—";
    const hist=$(".history-card");
    if(tests){
      const last=state.history[0];
      hist.querySelector("strong").textContent=tests+" test"+(tests===1?" completat":"s completats");
      hist.querySelector("p").textContent=last.date+" · "+last.law+" · "+last.percent+"% d'encerts";
      hist.querySelector(".history-icon").textContent="✓";
    } else {
      hist.querySelector("strong").textContent="Historial de pràctica";
      hist.querySelector("p").textContent="Quan completis un test, aquí veuràs els teus resultats.";
      hist.querySelector(".history-icon").textContent="↗";
    }
  }
  function shuffle(list){const a=[...list];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
  $$(".opposition-card").forEach(card=>card.addEventListener("click",()=>{$$(".opposition-card").forEach(c=>c.classList.toggle("selected",c===card));state.opposition=card.dataset.opposition;}));
  $$(".law-item").forEach(item=>item.addEventListener("click",()=>{$$(".law-item").forEach(c=>c.classList.toggle("selected",c===item));state.law=item.dataset.law;}));
  $("#lawSearch").addEventListener("input",e=>{const q=e.target.value.toLocaleLowerCase("ca").trim();$$(".law-item").forEach(item=>item.hidden=!item.textContent.toLocaleLowerCase("ca").includes(q));});
  $$(".count-option").forEach(btn=>btn.addEventListener("click",()=>{if(btn.classList.contains("premium-option")){message("Més preguntes amb Premium","Els tests de 30 i 50 preguntes formaran part de la subscripció. En aquesta demostració pots provar un test de 10 o 15 preguntes.");return;}$$(".count-option").forEach(b=>b.classList.toggle("active",b===btn));state.count=Number(btn.dataset.count);}));
  const premium=()=>message("OposiPrep Premium","La subscripció inclourà tests de diverses normes, sessions més llargues i seguiment ampliat. Els pagaments encara no estan activats: cal connectar un backend segur i un proveïdor de pagaments.");
  $("#upgradeTop").addEventListener("click",premium);$("#upgradeBottom").addEventListener("click",premium);$("#multiToggle").addEventListener("click",premium);$("#closeDialog").addEventListener("click",()=>dialog.close());
  function resetQuizBody(){
    $(".quiz-body").innerHTML='<p class="eyebrow" id="quizLawLabel"></p><h1 id="quizTitle"></h1><p class="quiz-instruction">Selecciona una única resposta.</p><div id="answerOptions" class="answer-options"></div><div id="answerFeedback" class="answer-feedback" hidden></div><div class="quiz-actions"><button class="button button-outline" id="prevQuestion">← Anterior</button><button class="button button-primary" id="nextQuestion">Comprovar resposta →</button></div>';
    $("#prevQuestion").addEventListener("click",previous);$("#nextQuestion").addEventListener("click",next);
  }
  function start(){
    if($("#lawText").value.trim()){message("Generació automàtica pendent","El text que enganxis no s'envia a cap servidor en aquesta demostració. Per generar preguntes a partir d'una norma cal connectar un servei d'IA al backend; aquesta funció encara no està activada.");return;}
    resetQuizBody();
    state.questions=shuffle(banks[state.law]||banks.constitucio).slice(0,Math.min(state.count,(banks[state.law]||banks.constitucio).length));state.index=0;state.answers={};state.checked={};
    $("#quizOverlay").hidden=false;document.body.style.overflow="hidden";render();
    if(state.count>state.questions.length)message("Mode demostració","Aquesta norma disposa de "+state.questions.length+" preguntes de mostra. El banc complet de preguntes encara s'ha d'ampliar.");
  }
  function render(){
    const q=state.questions[state.index],total=state.questions.length;
    $("#quizCounter").textContent="PREGUNTA "+(state.index+1)+" DE "+total;$("#quizPercent").textContent=Math.round((state.index+1)/total*100)+"%";$("#quizProgressBar").style.width=((state.index+1)/total*100)+"%";
    $("#quizLawLabel").textContent=names[state.law].toLocaleUpperCase("ca");$("#quizTitle").textContent=q[0];$("#answerFeedback").hidden=true;$("#answerFeedback").textContent="";
    const list=$("#answerOptions");list.replaceChildren();
    q[1].forEach((answer,i)=>{const b=document.createElement("button");b.type="button";b.className="answer-option";const letter=document.createElement("span");letter.className="answer-letter";letter.textContent=String.fromCharCode(65+i);const text=document.createElement("span");text.textContent=answer;b.append(letter,text);if(state.answers[state.index]===i)b.classList.add("chosen");if(state.checked[state.index]){b.disabled=true;if(i===q[2])b.classList.add("correct");else if(state.answers[state.index]===i)b.classList.add("wrong");}b.addEventListener("click",()=>{if(state.checked[state.index])return;state.answers[state.index]=i;$$(".answer-option",list).forEach(x=>x.classList.remove("chosen"));b.classList.add("chosen");});list.append(b);});
    $("#prevQuestion").disabled=state.index===0;$("#prevQuestion").style.opacity=state.index===0?".45":"1";$("#nextQuestion").textContent=state.checked[state.index]?(state.index===total-1?"Veure resultats →":"Següent pregunta →"):"Comprovar resposta →";
    if(state.checked[state.index]){const f=$("#answerFeedback");f.hidden=false;f.textContent=(state.answers[state.index]===q[2]?"Correcte. ":"Incorrecte. La resposta correcta és "+String.fromCharCode(65+q[2])+". ")+q[3];}
  }
  function results(){
    const total=state.questions.length,correct=state.questions.filter((q,i)=>state.answers[i]===q[2]).length,percent=Math.round(correct/total*100);
    state.history.unshift({date:new Date().toLocaleDateString("ca-ES"),law:names[state.law],correct,total,percent});
    state.history=state.history.slice(0,50);
    try { localStorage.setItem(HISTORY_KEY, JSON.stringify(state.history)); } catch (_) {}
    refreshStats();
    $("#quizCounter").textContent="TEST COMPLETAT";$("#quizPercent").textContent="100%";$("#quizProgressBar").style.width="100%";$("#quizLawLabel").textContent="RESULTAT · "+names[state.law].toLocaleUpperCase("ca");$("#quizTitle").textContent="Així ha anat aquesta sessió";$(".quiz-instruction").textContent="Has completat totes les preguntes.";
    $("#answerOptions").replaceChildren();$("#answerFeedback").hidden=true;
    const score=document.createElement("div");score.className="result-score";score.textContent=percent+"%";
    const summary=document.createElement("p");summary.className="result-message";summary.textContent=correct+" de "+total+" respostes correctes · "+(total-correct)+" per revisar.";
    const encouragement=document.createElement("p");encouragement.className="result-message";encouragement.textContent=percent>=80?"Molt bona feina! Continua repassant per consolidar els coneixements.":percent>=60?"Vas pel bon camí. Repassa les preguntes fallades i torna-ho a provar.":"Cada test és una oportunitat per millorar. Revisa les explicacions i practica de nou.";
    const review=document.createElement("div");review.className="result-review";const heading=document.createElement("h3");heading.textContent="Repàs de les respostes";review.append(heading);
    state.questions.forEach((q,i)=>{const row=document.createElement("div");row.className="review-item";const title=document.createElement("strong");title.textContent=(i+1)+". "+q[0];const detail=document.createElement("span");detail.textContent=(state.answers[i]===q[2]?"Correcte. ":"Incorrecte. Resposta correcta: "+String.fromCharCode(65+q[2])+". ")+q[1][q[2]]+" — "+q[3];row.append(title,detail);review.append(row);});
    const body=$(".quiz-body");body.append(score,summary,encouragement,review);
    const actions=$(".quiz-actions");actions.replaceChildren();const exit=document.createElement("button");exit.className="button button-outline";exit.textContent="Tornar a l'inici";exit.addEventListener("click",close);const retry=document.createElement("button");retry.className="button button-primary";retry.textContent="Repetir test →";retry.addEventListener("click",start);actions.append(exit,retry);
    refreshStats();
  }
  function close(){ $("#quizOverlay").hidden=true;document.body.style.overflow="";resetQuizBody();}
  function previous(){if(state.index>0){state.index--;render();}}
  function next(){if(!state.checked[state.index]){if(state.answers[state.index]===undefined){message("Tria una resposta","Selecciona una de les quatre opcions abans de continuar.");return;}state.checked[state.index]=true;render();return;}if(state.index<state.questions.length-1){state.index++;render();}else results();}
  $("#startTest").addEventListener("click",start);$("#prevQuestion").addEventListener("click",previous);$("#nextQuestion").addEventListener("click",next);
  $("#exitQuiz").addEventListener("click",()=>{if(confirm("Vols sortir del test? Perdràs el progrés d'aquesta sessió."))close();});
  refreshStats();
})();